/* ===== annonces de chasse : chasse à la journée / action de chasse ===== */
async function HaView(t){let kind="tous",tab="all",list=e("div.stack"),KL={journee:"Chasse à la journée",action:"Action de chasse"};
async function open1(a){try{let c=await v.post("/conversations",{memberIds:[a.author.id]});await v.post(`/conversations/${c.id}/messages`,{text:`Bonjour, votre annonce « ${a.title} » (${M.dateTime(a.date)}) m’intéresse. Reste-t-il une place ?`});ge("/messages/"+c.id)}catch(er){A(er.message,"err")}}
function card(a){let past=new Date(a.date).getTime()<Date.now(),closed=a.status!=="open";
return k({},e("div.row",{style:{gap:"8px",flexWrap:"wrap",alignItems:"center"}},L(KL[a.kind]||a.kind,a.kind==="journee"?"gold":"accent","flag"),closed?L("Clôturée","","check"):(past?L("Passée"):null),a.price?L(`Participation ${a.price} €`):L("Sans participation","accent")),
e("h3",{style:{margin:"10px 0 4px"}},a.title),
e("div.small",e("b",M.dateTime(a.date))),
e("div.small.muted",`${a.place}${a.department?" ("+a.department+")":""}${a.game?" · "+a.game:""} · ${a.spots} place${a.spots>1?"s":""}`),
a.description?e("p.small",{style:{margin:"10px 0 0",whiteSpace:"pre-wrap"}},a.description):null,
e("div.row",{style:{gap:"10px",marginTop:"12px",alignItems:"center",flexWrap:"wrap"}},oe(a.author,32),e("div.grow.small",e("b",a.author.name),e("div.tiny.muted",Ce(a.createdAt))),
a.mine?e("div.row",{style:{gap:"6px"}},x(closed?"Rouvrir":"Clôturer",{size:"sm",kind:"ghost",onClick:async()=>{await v.post(`/huntads/${a.id}/toggle`);load()}}),x("Supprimer",{size:"sm",kind:"ghost",icon:"trash",onClick:async()=>{await ve({title:"Supprimer cette annonce ?",text:"Elle sera retirée de la liste.",confirm:"Supprimer",danger:!0})&&(await v.del(`/huntads/${a.id}`),A("Annonce supprimée."),load())}})):(closed?null:x("Contacter",{size:"sm",kind:"primary",icon:"chat",onClick:()=>w.user?open1(a):ge("/connexion")}))))}
async function load(){let items=await v.get(`/huntads?kind=${kind}${tab==="mine"?"&mine=1":""}`);W(list);items.length?items.forEach(a=>C(list,card(a))):C(list,V({icon:"flag",title:tab==="mine"?"Vous n’avez publié aucune annonce":"Aucune annonce pour le moment",text:"Proposez une chasse à la journée ou une action de chasse : date, lieu, places et participation aux frais.",action:x("Publier une annonce",{icon:"plus",kind:"primary",onClick:add})}))}
async function add(){let r=await Q({title:"Nouvelle annonce de chasse",intro:"Votre annonce est visible de tous les membres. Les échanges se font par la messagerie.",submit:"Publier",wide:!0,fields:[{name:"kind",label:"Type",type:"seg",value:"journee",options:[["journee","Chasse à la journée"],["action","Action de chasse"]]},{name:"title",label:"Titre",required:!0,full:!0,placeholder:"Battue au sanglier, 3 places libres"},{name:"date",label:"Date et heure de rendez-vous",type:"datetime",required:!0,value:new Date(Date.now()+7*864e5).toISOString()},{name:"place",label:"Commune",required:!0,value:w.user.city||""},{name:"department",label:"Département",placeholder:"41"},{name:"game",label:"Gibier / type de chasse",placeholder:"Sanglier, chevreuil…"},{name:"spots",label:"Places disponibles",type:"number",min:1,value:2},{name:"price",label:"Participation aux frais (€)",type:"number",min:0,value:0,hint:"0 si gratuit. Il s’agit d’une participation à l’organisation, jamais d’une vente de gibier."},{name:"description",label:"Description",type:"textarea",placeholder:"Rendez-vous, terrain, consignes de sécurité, matériel demandé, chiens acceptés…"}],onSubmit:d=>v.post("/huntads",d)});r&&(A("Annonce publiée."),tab="mine",kind="tous",draw())}
const kf=()=>Je([["tous","Toutes"],["journee","À la journée"],["action","Actions de chasse"]],kind,z=>{kind=z;load()});
let head=e("div");function draw(){W(head);C(head,e("div.stack",Ne([["all","Annonces"],["mine","Mes annonces"]],tab,z=>{tab=z;load()}),kf()));load()}
C(t,q({title:"Annonces de chasse",subtitle:"Chasses à la journée et actions de chasse proposées par les membres.",actions:[x("Publier une annonce",{icon:"plus",kind:"primary",onClick:add})]},head,list,e("div.panel.tint",{style:{marginTop:"18px"}},e("div.row",b("info"),e("div.small","Le gibier prélevé ne se vend pas : une annonce ne peut demander qu’une participation aux frais. Vérifiez toujours le permis, l’assurance et les consignes de sécurité du responsable de la chasse avant de vous engager.")))));draw()}
var HaM={};le(HaM,{default:()=>HaView});var HaI=H(()=>{});
