/* ===== serveur : annonces de chasse (journée / action de chasse) ===== */
function HdSeed(){if(window.__hdS)return;window.__hdS=1;if(se.huntads.count())return;let us=se.users.all(),U=i=>(us[i%Math.max(us.length,1)]||{}).id,dd=(n,h)=>{let d=new Date(Date.now()+n*864e5);d.setHours(h,0,0,0);return d.toISOString()},ago=h=>new Date(Date.now()-h*36e5).toISOString();
se.huntads.insert({authorId:U(2),kind:"journee",title:"Journée de chasse au grand gibier en Sologne",date:dd(6,8),place:"Lamotte-Beuvron",department:"41",game:"Sanglier, chevreuil",spots:4,price:60,description:"Battue sur 300 ha de bois et de landes. Rendez-vous à 8 h au rond-point des Brosses, casse-croûte offert. Permis validé et assurance obligatoires.",status:"open",createdAt:ago(30)});
se.huntads.insert({authorId:U(1),kind:"action",title:"Action de chasse du samedi : chasse de petit gibier devant soi",date:dd(11,9),place:"Vouzon",department:"45",game:"Faisan, perdrix",spots:6,price:0,description:"Sortie entre chasseurs, en équipe de 8 maximum. Chiens d’arrêt bienvenus. Pas de participation demandée.",status:"open",createdAt:ago(12)});
se.huntads.insert({authorId:U(3),kind:"journee",title:"Battue au sanglier, 2 places libres",date:dd(3,7),place:"Souvigny-en-Sologne",department:"41",game:"Sanglier",spots:2,price:45,description:"Poste attribué par tirage au sort. Gilet orange obligatoire, sécurité rappelée au départ.",status:"open",createdAt:ago(5)})}
function HdOut(z,u){let a=se.users.get(z.authorId);return{id:z.id,kind:z.kind,title:z.title,date:z.date,place:z.place,department:z.department||"",game:z.game||"",spots:z.spots,price:z.price||0,description:z.description||"",status:z.status,createdAt:z.createdAt,mine:!!u&&z.authorId===u.id,author:a?_t(a):{id:z.authorId,name:"Ancien membre"}}}
Be.get("/huntads",bt(async(t,r)=>{HdSeed();let{kind:n,mine:m}=t.query,lim=Date.now()-864e5;r.json(se.huntads.all(z=>m?z.authorId===t.user.id:(z.status==="open"&&new Date(z.date).getTime()>=lim)).filter(z=>!n||n==="tous"||z.kind===n).sort((a,b2)=>m?b2.createdAt.localeCompare(a.createdAt):a.date.localeCompare(b2.date)).map(z=>HdOut(z,t.user)))}));
Be.post("/huntads",bt(async(t,r)=>{HdSeed();yr(t.body,{title:"string",kind:"string"});let b0=t.body,ti=String(b0.title).trim(),pl=String(b0.place||"").trim(),d=new Date(b0.date);if(ti.length<6)throw new lt(400,"Le titre est trop court (6 caractères minimum).",{fields:{title:"Trop court"}});if(!["journee","action"].includes(b0.kind))throw new lt(400,"Type d’annonce inconnu.");if(!b0.date||isNaN(d))throw new lt(400,"Indiquez la date et l’heure.",{fields:{date:"Date obligatoire"}});if(d.getTime()<Date.now()-36e5)throw new lt(400,"La date doit être à venir.",{fields:{date:"Date passée"}});if(!pl)throw new lt(400,"Indiquez la commune.",{fields:{place:"Obligatoire"}});if(se.huntads.count(z=>z.authorId===t.user.id&&z.status==="open")>=10)throw new lt(400,"Vous avez déjà 10 annonces ouvertes : clôturez-en une avant d’en publier.");
r.status(201).json(HdOut(se.huntads.insert({authorId:t.user.id,kind:b0.kind,title:ti.slice(0,120),date:d.toISOString(),place:pl.slice(0,80),department:String(b0.department||"").trim().slice(0,3),game:String(b0.game||"").trim().slice(0,80),spots:Math.max(1,Math.min(99,Math.round(+b0.spots||1))),price:Math.max(0,Math.min(1000,Math.round(+b0.price||0))),description:String(b0.description||"").trim().slice(0,1200),status:"open",createdAt:new Date().toISOString()}),t.user))}));
Be.post("/huntads/:id/toggle",bt(async(t,r)=>{let z=se.huntads.get(t.params.id);if(!z||z.authorId!==t.user.id)throw new lt(404,"Annonce introuvable.");r.json(HdOut(se.huntads.update(z.id,{status:z.status==="open"?"closed":"open"}),t.user))}));
Be.delete("/huntads/:id",bt(async(t,r)=>{let z=se.huntads.get(t.params.id);if(!z||z.authorId!==t.user.id&&!["admin","moderator"].includes(t.user.role))throw new lt(404,"Annonce introuvable.");se.huntads.remove(z.id);r.json({ok:!0})}));
