/* ===== 3.0 : console administrateur (graphiques) ===== */
function ChSvg(h){let d=document.createElement("div");d.innerHTML=h;return d.firstElementChild}
function ChEsc(s1){return String(s1).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c])}
function ChNice(mx){if(mx<=4)return 4;let p=Math.pow(10,Math.floor(Math.log10(mx))),f=mx/p;return(f<=1?1:f<=2?2:f<=5?5:10)*p}
function ChDate(ts){return new Date(ts).toLocaleDateString("fr-FR",{day:"numeric",month:"short"})}
function ChLine(data,o){o=o||{};let W=640,H=o.h||210,pl=34,pr=10,pt1=12,pb=26,n=data.length,mx=ChNice(Math.max(1,...data.map(d=>d.value))),X=i=>pl+(n<2?0:i*(W-pl-pr)/(n-1)),Y=v1=>pt1+(H-pt1-pb)*(1-v1/mx),col=o.color||"var(--accent)",grid=[0,.5,1].map(f=>{let y=Y(mx*f);return`<line x1="${pl}" x2="${W-pr}" y1="${y}" y2="${y}" stroke="var(--line)" stroke-width="1"/><text x="${pl-6}" y="${y+4}" text-anchor="end" font-size="11" fill="var(--muted)">${Math.round(mx*f)}</text>`}).join(""),pts=data.map((d,i)=>[X(i),Y(d.value)]),line=pts.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+" "+p[1].toFixed(1)).join(" "),area=n?line+` L${X(n-1)} ${Y(0)} L${X(0)} ${Y(0)} Z`:"",idx=n<=1?[0]:[0,Math.floor((n-1)/2),n-1],xl=idx.map(i=>`<text x="${X(i)}" y="${H-6}" text-anchor="${i===0?"start":i===n-1?"end":"middle"}" font-size="11" fill="var(--muted)">${ChEsc(o.xfmt?o.xfmt(data[i]):data[i].label)}</text>`).join(""),dots=data.length<=40?pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3.5" fill="var(--surface)" stroke="${col}" stroke-width="2"><title>${ChEsc(o.xfmt?o.xfmt(data[i]):data[i].label)} : ${data[i].value}</title></circle>`).join(""):"";
return ChSvg(`<svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="${ChEsc(o.label||"Courbe")}" style="display:block;overflow:visible">${grid}<path d="${area}" fill="${col}" fill-opacity=".12"/><path d="${line}" fill="none" stroke="${col}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>${dots}${xl}</svg>`)}
function ChBars(data,o){o=o||{};let W=640,H=o.h||190,pl=34,pr=6,pt1=12,pb=26,n=data.length,mx=ChNice(Math.max(1,...data.map(d=>d.value))),bw=(W-pl-pr)/Math.max(n,1),Y=v1=>pt1+(H-pt1-pb)*(1-v1/mx),col=o.color||"var(--moss)",grid=[0,.5,1].map(f=>{let y=Y(mx*f);return`<line x1="${pl}" x2="${W-pr}" y1="${y}" y2="${y}" stroke="var(--line)"/><text x="${pl-6}" y="${y+4}" text-anchor="end" font-size="11" fill="var(--muted)">${Math.round(mx*f)}</text>`}).join(""),bars=data.map((d,i)=>{let x1=pl+i*bw+bw*.18,w1=bw*.64,y=Y(d.value);return`<rect x="${x1.toFixed(1)}" y="${y.toFixed(1)}" width="${w1.toFixed(1)}" height="${Math.max(0,Y(0)-y).toFixed(1)}" rx="3" fill="${col}"><title>${ChEsc(o.xfmt?o.xfmt(d):d.label)} : ${d.value}</title></rect>`}).join(""),step=Math.ceil(n/6),xl=data.map((d,i)=>i%step===0||i===n-1?`<text x="${pl+i*bw+bw/2}" y="${H-6}" text-anchor="middle" font-size="11" fill="var(--muted)">${ChEsc(o.xfmt?o.xfmt(d):d.label)}</text>`:"").join("");
return ChSvg(`<svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="${ChEsc(o.label||"Histogramme")}" style="display:block">${grid}${bars}${xl}</svg>`)}
function ChDonut(data,o){o=o||{};let tot=data.reduce((s1,d)=>s1+d.value,0),R=54,C1=2*Math.PI*R,off=0,cols=["var(--accent)","var(--moss)","var(--river)","var(--gold)","var(--wood)"],arcs=data.map((d,i)=>{let len=tot?C1*d.value/tot:0,a=`<circle cx="70" cy="70" r="${R}" fill="none" stroke="${cols[i%cols.length]}" stroke-width="22" stroke-dasharray="${len.toFixed(2)} ${(C1-len).toFixed(2)}" stroke-dashoffset="${(-off).toFixed(2)}" transform="rotate(-90 70 70)"><title>${ChEsc(d.label)} : ${d.value}</title></circle>`;off+=len;return a}).join("");
return e("div.donut-wrap",ChSvg(`<svg viewBox="0 0 140 140" width="150" height="150" role="img" aria-label="${ChEsc(o.label||"Répartition")}"><circle cx="70" cy="70" r="${R}" fill="none" stroke="var(--surface-3)" stroke-width="22"/>${arcs}<text x="70" y="68" text-anchor="middle" font-size="26" font-weight="700" fill="var(--text)" font-family="var(--font-display)">${tot}</text><text x="70" y="86" text-anchor="middle" font-size="11" fill="var(--muted)">${ChEsc(o.center||"total")}</text></svg>`),e("div.donut-legend",data.map((d,i)=>e("div.row",{style:{gap:"8px"}},e("i",{style:{width:"12px",height:"12px",borderRadius:"3px",background:cols[i%cols.length],display:"inline-block",flex:"none"}}),e("span.grow",d.label),e("b.mono-num",String(d.value))))))}
async function AdmDashV3(t,s0){let s=s0,days=Pe.get("adm:days",30),root=e("div.stack"),DEPT={"41":"Loir-et-Cher","45":"Loiret","37":"Indre-et-Loire","18":"Cher","36":"Indre","28":"Eure-et-Loir","72":"Sarthe","49":"Maine-et-Loire","85":"Vendée","33":"Gironde","40":"Landes"},todo=s.content.articlesPending+s.reportsOpen+s.alertsOpen+s.zonesToReview,cd=(h,l,n)=>e("a.adm-todo",{href:h,class:n?"on":""},e("b",String(n)),e("span",l)),stamp=e("span.tiny.muted","");
let draw=async()=>{let an;try{an=await v.get("/admin/analytics?days="+days)}catch(er){W(root);C(root,V({icon:"alert",title:"Statistiques indisponibles",text:er.message}));return}W(root);stamp.textContent="Mis à jour à "+new Date().toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"});
let sum=a=>a.reduce((s1,d)=>s1+d.value,0),su=sum(an.signups),prev=an.signupsPrev,delta=prev?Math.round((su-prev)/prev*100):null,act=sum(an.activity),dd=d=>ChDate(d.t),wk=an.content.map(w1=>({label:ChDate(w1.t),t:w1.t,value:w1.posts+w1.catches+w1.articles}));
C(root,
e("div.grid.g-4",k({},ee(M.num(s.users),"Utilisateurs",{delta:`+${s.newUsers30} sur 30 jours`,deltaTone:"ok"})),k({},ee(M.num(s.paid),"Abonnés payants",{delta:`${s.conversion} % de conversion`,deltaTone:"ok"})),k({},ee(M.euro(s.arr),"Revenu annuel récurrent",{delta:"abonnements particuliers"})),k({},ee(M.num(an.activeUsers),"Membres actifs (30 j)",{delta:`${an.users?Math.round(an.activeUsers/an.users*100):0} % des inscrits`}))),
k({title:"À traiter",sub:String(todo)},e("div.adm-todos",cd("#/admin/articles","Articles à valider",s.content.articlesPending),cd("#/admin/signalements","Signalements ouverts",s.reportsOpen),cd("#/admin/zones","Zones saisies à contrôler",s.zonesToReview),cd("#/securite","Alertes terrain ouvertes",s.alertsOpen))),
e("div.grid.g-2",k({title:"Inscriptions",sub:`${su} sur ${days} jours${delta==null?"":` · ${delta>=0?"+":""}${delta} % vs période précédente`}`},ChLine(an.signups,{label:"Inscriptions par jour",xfmt:dd})),k({title:"Activité des membres",sub:`${act} actions sur 14 jours`},ChBars(an.activity,{label:"Actions par jour (publications, commentaires, prises, alertes)",xfmt:dd,color:"var(--river)"}))),
e("div.grid.g-3",k({title:"Abonnés par offre"},ChDonut(s.byPlan.map(p=>({label:p.name,value:p.count})),{label:"Répartition par offre",center:"comptes"})),k({title:"Profils"},pt(s.byProfile.map(p=>({label:AdmProf[p.profile]||p.profile,value:p.count})))),k({title:"Départements",sub:"Top 6"},an.byDept.length?pt(an.byDept.map(d=>({label:d.code+(DEPT[d.code]?" · "+DEPT[d.code]:""),value:d.count}))):e("p.small.muted",{style:{margin:0}},"Pas de département renseigné."))),
e("div.grid.g-2",k({title:"Du compte à l’abonnement",sub:"Entonnoir"},pt([{label:"Inscrits",value:an.users,tone:"accent"},{label:"Actifs sur 30 j",value:an.activeUsers,tone:"accent"},{label:"Abonnés payants",value:s.paid,tone:"gold"}],{max:Math.max(1,an.users)})),k({title:"Contenus publiés par semaine",sub:"Publications, prises et articles"},ChBars(wk,{label:"Contenus par semaine",xfmt:d=>d.label,color:"var(--moss)",h:170}))),
e("div.grid.g-2",k({title:"Derniers inscrits",flush:!0,action:e("a.link-more",{href:"#/admin/utilisateurs"},"Tous",b("chevron"))},$e([{label:"Membre",render:u=>e("div.row",{style:{gap:"10px"}},oe(u,32),e("div",e("b",u.name),e("div.tiny.muted",u.city||"—")))},{label:"Offre",render:u=>L(u.planName||u.plan,u.plan==="free"?"":"gold")},{label:"Inscrit",render:u=>Ce(u.createdAt)}],an.recentUsers)),k({title:"Dernières alertes et signalements",flush:!0,action:e("a.link-more",{href:"#/securite"},"Sécurité",b("chevron"))},an.recentEvents.length?e("div.list",an.recentEvents.map(a=>e("a.list-row",{href:a.link},e("span.ic",{style:{color:a.tone==="danger"?"var(--brick)":"var(--warn)"}},b(a.kind==="sos"?"sos":"alert")),e("div.grow",e("div.t",a.title),e("div.s",a.sub)),e("div.end.small.muted",Ce(a.createdAt))))):e("p.small.muted",{style:{padding:"16px",margin:0}},"Rien à signaler."))),
k({title:"Offres et abonnements",flush:!0},$e([{label:"Offre",render:p=>e("b",p.name)},{label:"Prix",render:p=>p.price?`${M.euro(p.price)} / ${AdmPer[p.period]||p.period||"an"}`:"Gratuit"},{label:"Abonnés",num:!0,key:"count"},{label:"Revenu annuel",num:!0,render:p=>M.euro(p.revenue)}],s.byPlan)),
e("div.grid.g-4",[["Publications",s.content.posts],["Prises au carnet",s.content.catches],["Recettes",s.content.recipes],["Articles publiés",s.content.articles]].map(([l,n])=>k({},ee(n,l)))))};
C(t,q({title:"Tableau de bord",subtitle:"Vue d’ensemble de la plateforme · "+new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"}),actions:[x("Actualiser",{icon:"locate",kind:"ghost",onClick:()=>draw()}),x("Exporter CSV",{icon:"download",kind:"ghost",onClick:async()=>{try{let an=await v.get("/admin/analytics?days="+days);CsvModal("inscriptions",[["Jour","Inscriptions"],...an.signups.map(d=>[new Date(d.t).toISOString().slice(0,10),d.value])])}catch(er){A(er.message,"err")}}})]},e("div.toolbar",e("span.small.muted","Période des inscriptions"),ke([["7","7 jours"],["30","30 jours"],["90","90 jours"]],String(days),z=>{days=+z;Pe.set("adm:days",days);draw()}),e("div.grow"),stamp),root));await draw()}
