xe.get("/admin/analytics",et(async(t,r)=>{km(t);if(t.user.role!=="admin")throw new nn(403,"Réservé aux administrateurs.");let days=Math.min(90,Math.max(7,+t.query.days||30)),DAY=864e5,d0=new Date;d0.setHours(0,0,0,0);d0=+d0;
let bucket=(items,n,off=0)=>{let st=d0-(n-1+off)*DAY,out=Array.from({length:n},(_,i)=>({t:st+i*DAY,value:0}));items.forEach(a=>{let i=Math.floor((+new Date(a.createdAt)-st)/DAY);i>=0&&i<n&&out[i].value++});return out},
us=z.users.all(),posts=z.posts.all(),comments=z.comments.all(),catches=z.catches.all(),alerts=z.alerts.all(),arts=z.articles.all(a=>a.status==="published"),reps=z.reports.all(),
who=a=>a.authorId||a.userId||a.ownerId,recent30=a=>Date.now()-new Date(a.createdAt)<30*DAY,act=new Set;[posts,comments,catches,alerts].forEach(ls=>ls.filter(recent30).forEach(a=>{let w1=who(a);w1&&act.add(w1)}));
let dep={};us.forEach(u=>{if(u.department)dep[u.department]=(dep[u.department]||0)+1});
let weeks=Array.from({length:8},(_,i)=>{let to=d0+DAY-(7-i-1)*7*DAY,from=to-7*DAY,inW=a=>{let d=+new Date(a.createdAt);return d>=from&&d<to};return{t:from,posts:posts.filter(inW).length,catches:catches.filter(inW).length,articles:arts.filter(inW).length}}),
PL=$n,ev=[...alerts.map(a=>({kind:a.type==="sos"?"sos":"alert",tone:a.type==="sos"?"danger":"warn",title:(a.category||"Alerte")+(a.status==="open"?"":" (clôturée)"),sub:String(a.text||"").slice(0,70),createdAt:a.createdAt,link:"#/securite/"+a.id})),...reps.filter(q=>q.status==="open").map(q=>({kind:"report",tone:"warn",title:"Signalement : "+(q.reason||""),sub:String(q.details||"").slice(0,70),createdAt:q.createdAt,link:"#/admin/signalements"}))].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,6);
r.json({users:us.length,activeUsers:act.size,signups:bucket(us,days),signupsPrev:us.filter(u=>{let d=Date.now()-new Date(u.createdAt);return d>=days*DAY&&d<2*days*DAY}).length,activity:bucket([...posts,...comments,...catches,...alerts],14),byDept:Object.entries(dep).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([code,count])=>({code,count})),content:weeks,recentUsers:us.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,6).map(u=>({id:u.id,name:u.name,city:u.city,plan:u.plan,planName:(PL[u.plan]||{}).name,createdAt:u.createdAt})),recentEvents:ev})}));
function AdmSeed(){if(window.__admS)return;window.__admS=1;if(z.users.count(u=>u.demoSeed))return;let fn=["Julien","Camille","Antoine","Léa","Hugo","Manon","Thomas","Chloé","Nicolas","Sarah","Mathieu","Emma","Pierre","Inès","Lucas","Laura","Romain","Pauline","Kevin","Marion","David","Julie","Sébastien","Alice","Fabien","Clara"],ln=["Moreau","Lefèvre","Bertrand","Roux","Fournier","Girard","Bonnet","Dupuis","Lambert","Fontaine","Chevalier","Garnier","Faure","Mercier","Blanc","Guerin","Muller","Henry","Perrin","Morel"],ct=[["41","Blois"],["41","Romorantin"],["41","Vendôme"],["45","Orléans"],["45","Gien"],["37","Tours"],["18","Bourges"],["36","Châteauroux"],["28","Chartres"],["72","Le Mans"]],pr=["chasseur","pecheur","mixte","usager"],pl=["free","free","free","free","free","free","free","chasse","peche","combo"],seed=7,rnd=()=>(seed=(seed*9301+49297)%233280)/233280;
for(let i=0;i<26;i++){let f=fn[i%fn.length],l=ln[Math.floor(rnd()*ln.length)],c=ct[Math.floor(rnd()*ct.length)],ago=Math.floor(Math.pow(rnd(),1.7)*88)+1,d=new Date(Date.now()-ago*864e5-Math.floor(rnd()*864e5));z.users.insert({id:"u_demo"+i,email:(f+"."+l+i+"@demo.invalid").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,""),name:f+" "+l,profile:pr[Math.floor(rnd()*4)],plan:pl[Math.floor(rnd()*pl.length)],role:"user",city:c[1],department:c[0],bio:"",badges:[],demoSeed:!0,createdAt:d.toISOString()})}}
