var BAG_SP=["Sanglier","Chevreuil","Cerf","Daim","Mouflon","Renard","Lièvre","Lapin de garenne","Faisan","Perdrix","Bécasse","Canard colvert","Pigeon ramier","Autre"],BAG_MODES=["Battue","Approche","Affût / poste fixe","Chasse devant soi","Chasse au vol","Autre"];
function BagKey(){return"bag."+((w.user&&w.user.id)||"anon")}
function BagLoad(){return Pe.get(BagKey(),[])}
function BagSave(a){Pe.set(BagKey(),a)}
function BagSeason(d){let t=new Date(d),y=t.getFullYear(),m=t.getMonth();return m>=6?`${y}–${y+1}`:`${y-1}–${y}`}
async function BagAdd(done){let p=w.position||{lat:47.6445,lng:2.181};try{let g=await Ee(2500);g&&g.lat!=null&&(p=g)}catch{}
let r=await Q({title:"Nouveau tableau de chasse",intro:"Notez un animal ou un lot prélevé. La position GPS est ajoutée automatiquement.",submit:"Enregistrer",wide:!0,fields:[{name:"species",label:"Espèce",type:"chips",required:!0,options:BAG_SP.map(i=>[i,i])},{name:"count",label:"Nombre",type:"number",min:1,step:1,value:1},{name:"weight",label:"Poids (kg, facultatif)",type:"number",min:0,step:0.5},{name:"mode",label:"Mode de chasse",type:"select",placeholder:"—",options:BAG_MODES},{name:"place",label:"Lieu (facultatif)",placeholder:"Bois des Brosses, poste 4…"},{name:"tag",label:"N° de bracelet (facultatif)"},{name:"date",label:"Date et heure",type:"datetime",value:new Date().toISOString()},{name:"photo",label:"Photo",type:"photo"},{name:"notes",label:"Notes",type:"textarea",placeholder:"Sexe, âge estimé, conditions, tir…"}],onSubmit:async i=>{let a=BagLoad();a.push({id:"b"+Date.now().toString(36),species:i.species,count:+i.count||1,weight:i.weight?+i.weight:null,mode:i.mode||"",place:i.place||"",tag:i.tag||"",date:i.date||new Date().toISOString(),photo:i.photo||"",notes:i.notes||"",location:{lat:p.lat,lng:p.lng}});BagSave(a)}});
if(r){A("Prélèvement noté dans votre tableau de chasse.");done&&done()}return r}
async function BagView(t){let flt="",seas="",root=e("div"),st=e("div.stack");
function items(){return BagLoad().sort((a,b)=>b.date.localeCompare(a.date))}
function detail(p){let m=Le({title:`${p.species}${p.count>1?` · ${p.count}`:""}`,wide:!0,body:e("div.stack",p.photo?e("div.photo",e("img",{src:p.photo,alt:p.species})):null,rt([["Date",M.dateTime(p.date)],["Espèce",p.species],["Nombre",String(p.count)],["Poids",p.weight?`${p.weight} kg`:"—"],["Mode de chasse",p.mode||"—"],["Lieu",p.place||"—"],["N° de bracelet",p.tag||"—"],["Coordonnées",p.location?e("span.mono-num",`${p.location.lat.toFixed(5)}, ${p.location.lng.toFixed(5)}`):"—"],["Notes",p.notes||"—"]])),actions:[x("Supprimer",{kind:"ghost",icon:"trash",onClick:async()=>{await ve({title:"Supprimer ce prélèvement ?",text:"Il sera retiré de votre tableau de chasse et de vos statistiques.",confirm:"Supprimer",danger:!0})&&(BagSave(BagLoad().filter(z=>z.id!==p.id)),m.close(),A("Prélèvement supprimé."),draw())}}),p.location?x("Voir sur la carte",{icon:"map",href:`#/carte?focus=${p.location.lat},${p.location.lng}`}):null].filter(Boolean)})}
function draw(){let all=items(),seasons=[...new Set(all.map(i=>BagSeason(i.date)))],species=[...new Set(all.map(i=>i.species))];
let cur=all.filter(i=>(!flt||i.species===flt)&&(!seas||BagSeason(i.date)===seas));
W(root);
if(!all.length){C(root,V({icon:"flag",title:"Votre tableau de chasse est vide",text:"Notez vos prélèvements : espèce, nombre, poids, lieu, bracelet. Les statistiques se construisent toutes seules.",action:x("Noter un prélèvement",{icon:"plus",kind:"primary",onClick:()=>BagAdd(draw)})}));return}
let tot=cur.reduce((s,i)=>s+i.count,0),days=new Set(cur.map(i=>i.date.slice(0,10))).size,kg=cur.reduce((s,i)=>s+(i.weight||0),0);
let by={};cur.forEach(i=>{by[i.species]=(by[i.species]||0)+i.count});let bs=Object.entries(by).sort((a,b)=>b[1]-a[1]);
let mo=Array(12).fill(0);cur.forEach(i=>{mo[new Date(i.date).getMonth()]+=i.count});
let order=[6,7,8,9,10,11,0,1,2,3,4,5],ml=["J","F","M","A","M","J","J","A","S","O","N","D"];
let filters=e("div.row",{style:{gap:"8px",flexWrap:"wrap"}},e("select.input",{style:{maxWidth:"220px"},"aria-label":"Saison de chasse",onchange:ev=>{seas=ev.target.value;draw()}},e("option",{value:""},"Toutes les saisons"),seasons.map(s=>e("option",{value:s,selected:s===seas},`Saison ${s}`))),e("select.input",{style:{maxWidth:"220px"},"aria-label":"Espèce",onchange:ev=>{flt=ev.target.value;draw()}},e("option",{value:""},"Toutes les espèces"),species.map(s=>e("option",{value:s,selected:s===flt},s))));
C(root,e("div.stack",e("div.grid.g-2",it(tot,"Animaux prélevés"),it(days,"Jours de chasse")),kg?e("div.grid.g-2",it(M.num(Math.round(kg)),"kg cumulés"),it(bs.length,"Espèce(s)")):null,filters,
k({title:"Tableau",sub:`${cur.length} ligne(s)`},$e([{label:"Date",render:m=>e("div",e("b",M.dateShort(m.date)),e("div.tiny.muted",M.time(m.date)))},{label:"Espèce",render:m=>e("div",e("b",m.species),m.tag?e("div.tiny.muted",`Bracelet ${m.tag}`):null)},{label:"Nb",num:!0,render:m=>String(m.count)},{label:"Poids",num:!0,render:m=>m.weight?`${m.weight} kg`:"—"},{label:"Lieu / mode",render:m=>e("div",m.place||"—",m.mode?e("div.tiny.muted",m.mode):null)},{label:"",render:m=>e("div.row",{style:{justifyContent:"flex-end"}},e("button.icon-btn",{type:"button","aria-label":"Détail",title:"Détail",onclick:()=>detail(m)},b("chevron")))}],cur,{empty:"Aucun prélèvement pour ce filtre."})),
k({title:"Par espèce"},bs.length?pt(bs.map(([l,v2])=>({label:l,value:v2}))):e("p.muted","—")),
k({title:"Par mois",sub:"de juillet à juin"},On(order.map(m=>({label:ml[m],value:mo[m]}))))))}
C(t,q({title:"Tableau de chasse",subtitle:"Votre carnet personnel de prélèvements, avec statistiques par saison et par espèce. Il reste sur cet appareil.",actions:[x("Noter un prélèvement",{icon:"plus",kind:"primary",onClick:()=>BagAdd(draw)})]},root));draw()}
var BagM={};le(BagM,{default:()=>BagView});var BagI=H(()=>{});
