/* ===== 3.0 : amis ===== */
var __frLast="";
function FrPref(){return !!Pe.get("friends-share:"+(w.user&&w.user.id),!1)}
function FrSync(t){if(!w.user)return;let body=FrPref()&&t&&t.status==="active"?{active:!0,activity:t.activity==="peche"?"peche":t.activity==="nature"?"nature":"chasse",returnAt:t.returnAt}:{active:!1},k1=JSON.stringify(body);if(k1===__frLast)return;__frLast=k1;try{v.post("/friends/status",body).catch(()=>{})}catch{}}
function FrFirst(u){return String(u&&u.name||"").split(" ")[0]||"ami"}
async function FrMessage(u,text){let c=await v.post("/conversations",{memberIds:[u.id]});if(text)await v.post("/conversations/"+c.id+"/messages",{text:text});return c}
async function FrInvite(u){let pe=w.season==="peche",ok=await Q({title:"Inviter "+FrFirst(u)+" à une sortie",intro:"Un message est envoyé dans votre messagerie. Il ne contient aucune position.",submit:"Envoyer l’invitation",
fields:[{name:"activity",label:"Activité",type:"select",required:!0,value:pe?"peche":"chasse",options:[{value:"chasse",label:"Chasse"},{value:"peche",label:"Pêche"},{value:"nature",label:"Balade nature"}]},{name:"when",label:"Quand ?",required:!0,placeholder:"Samedi matin, dimanche 8 h…"},{name:"place",label:"Où ? (facultatif)",placeholder:"Sologne, étang des Brosses…"},{name:"note",label:"Un mot (facultatif)",type:"textarea"}],
onSubmit:async d=>{let verb={chasse:"chasser",peche:"pêcher",nature:"me balader"}[d.activity]||"sortir",tx="Salut "+FrFirst(u)+", je pars "+verb+" "+String(d.when).trim()+(d.place?" du côté de "+String(d.place).trim():"")+". Tu es partant ?"+(d.note?"\n"+String(d.note).trim():"");let c=await FrMessage(u,tx);window.__frGo=c.id}});
if(ok){A("Invitation envoyée à "+FrFirst(u)+".","ok");let id=window.__frGo;window.__frGo=null;if(id)ge("/messages/"+id)}}
function FrStatusPill(s){if(!s)return null;let hm=TripHm(s.returnAt);return L("En sortie "+TripAct(s.activity)+(s.late?" · retour dépassé":" · retour vers "+hm),s.late?"warn":"ok")}
function FrRow(c,actions,sub){let u=c.user,st=FrStatusPill(c.status);return e("div.panel",{style:{padding:"14px"}},e("div",{style:{display:"flex",gap:"12px",alignItems:"center",flexWrap:"wrap"}},e("a",{href:"#/profil/"+u.id,style:{display:"flex",flexShrink:0},"aria-label":"Profil de "+u.name},oe(u,52)),e("div",{style:{flex:"1 1 160px",minWidth:0}},e("a",{href:"#/profil/"+u.id,style:{fontWeight:700,fontSize:"17px",color:"inherit",textDecoration:"none"}},u.name),e("div.small.muted",[u.city,c.mutual?c.mutual+" ami"+(c.mutual>1?"s":"")+" en commun":null].filter(Boolean).join(" · ")),sub?e("div.small.muted",sub):null,st?e("div",{style:{marginTop:"6px"}},st):null),e("div",{style:{display:"flex",gap:"8px",flexWrap:"wrap"}},actions)))}
async function FriendsView(t){
let u=w.user,tab="amis",data=null,qv="",resBox=e("div.stack",{style:{marginTop:"12px"}}),body=e("div.stack"),side=e("div.stack"),head=e("div"),tmr=null;
let reload=async()=>{try{data=await v.get("/friends")}catch(er){A(er.message,"err");return}draw()},
act=async(fn,msg)=>{try{await fn();msg&&A(msg,"ok")}catch(er){A(er.message,"err")}await reload()},
msgBtn=c=>x("Message",{icon:"chat",size:"sm",onClick:async()=>{let m=await FrMessage(c.user);ge("/messages/"+m.id)}}),
tabs=()=>ke([["amis","Amis"+(data?" · "+data.friends.length:"")],["demandes","Demandes"+(data&&data.received.length?" · "+data.received.length:"")],["trouver","Trouver"]],tab,z=>{tab=z;draw()}),
friendsTab=()=>data.friends.length?e("div.stack",data.friends.map(c=>FrRow(c,[msgBtn(c),x("Inviter",{icon:"send",size:"sm",onClick:()=>FrInvite(c.user)}),e("button.icon-btn",{type:"button","aria-label":"Retirer "+c.user.name+" de mes amis",title:"Retirer de mes amis",onclick:async()=>{if(await ve({title:"Retirer "+c.user.name+" de vos amis ?",text:"Vous ne verrez plus vos sorties respectives. Vous pourrez le réinviter plus tard.",confirm:"Retirer",danger:!0}))act(()=>v.del("/friends/user/"+c.user.id),"Ami retiré.")}},b("trash"))],"Ami depuis le "+M.dateShort(c.since)))):V({icon:"users",title:"Pas encore d’amis ici",text:"Ajoutez vos partenaires de chasse ou de pêche : vous pourrez leur écrire, les inviter en sortie et suivre leurs publications.",action:x("Trouver des amis",{kind:"primary",icon:"search",onClick:()=>{tab="trouver";draw()}})}),
reqTab=()=>e("div.stack",{style:{gap:"18px"}},e("div.stack",e("h3.display",{style:{margin:0,fontSize:"20px"}},"Reçues"),data.received.length?data.received.map(c=>FrRow(c,[x("Accepter",{icon:"check",size:"sm",kind:"primary",onClick:()=>act(()=>v.post("/friends/"+c.id+"/accept"),"Vous êtes maintenant amis avec "+FrFirst(c.user)+".")}),x("Refuser",{size:"sm",kind:"ghost",onClick:()=>act(()=>v.post("/friends/"+c.id+"/decline"),"Demande refusée.")})],"Il y a "+Math.max(1,Math.round((Date.now()-new Date(c.createdAt))/36e5))+" h")):e("p.small.muted",{style:{margin:0}},"Aucune demande en attente.")),
data.sent.length?e("div.stack",e("h3.display",{style:{margin:0,fontSize:"20px"}},"Envoyées"),data.sent.map(c=>FrRow(c,[x("Annuler",{size:"sm",kind:"ghost",onClick:()=>act(()=>v.post("/friends/"+c.id+"/decline"),"Demande annulée.")})],"En attente de réponse"))):null),
addBtn=(c,state)=>state==="friends"?L("Ami","ok"):state==="sent"?L("Demande envoyée"):x(state==="received"?"Accepter":"Ajouter",{icon:state==="received"?"check":"plus",size:"sm",kind:"primary",onClick:()=>act(()=>v.post("/friends/request",{userId:c.user.id}),state==="received"?"Vous êtes maintenant amis.":"Demande envoyée à "+FrFirst(c.user)+".")}),
doSearch=async()=>{W(resBox);if(qv.trim().length<2){C(resBox,e("p.small.muted",{style:{margin:0}},"Tapez au moins 2 lettres du nom ou de la commune."));return}let r=await v.get("/friends/search?q="+encodeURIComponent(qv.trim()));C(resBox,r.length?r.map(c=>FrRow(c,[addBtn(c,c.state)])):V({icon:"search",title:"Aucun membre trouvé",text:"Vérifiez l’orthographe ou essayez une commune."}))},
findTab=()=>{let box=e("div.stack",xt("Rechercher un membre par nom ou commune",z=>{qv=z;clearTimeout(tmr);tmr=setTimeout(doSearch,250)},qv),resBox);W(resBox);qv?doSearch():null;return e("div.stack",{style:{gap:"18px"}},box,data.suggestions.length&&!qv?e("div.stack",e("h3.display",{style:{margin:0,fontSize:"20px"}},"Suggestions"),data.suggestions.map(c=>FrRow(c,[addBtn(c,"none")],c.reason))):null)},
draw=()=>{W(head);C(head,tabs());W(body);C(body,tab==="amis"?friendsTab():tab==="demandes"?reqTab():findTab());drawSide()},
drawSide=()=>{W(side);let out=data.friends.filter(c=>c.status),on=FrPref(),cb=e("input",{type:"checkbox",checked:on,onchange:async ev=>{Pe.set("friends-share:"+u.id,ev.target.checked);let tr=TripGet();__frLast="";FrSync(tr);A(ev.target.checked?"Vos amis verront vos prochaines sorties.":"Vos sorties restent privées.","ok");drawSide()}});
C(side,k({title:"En sortie maintenant",sub:out.length?out.length+" ami"+(out.length>1?"s":""):"",action:e("a.link-more",{href:"#/suivi"},"Suivi en direct",b("chevron"))},out.length?e("div.stack",{style:{gap:"10px"}},out.map(c=>e("a",{href:"#/profil/"+c.user.id,style:{display:"flex",gap:"10px",alignItems:"center",color:"inherit",textDecoration:"none"}},oe(c.user,36),e("div",{style:{minWidth:0}},e("b",c.user.name),e("div.small.muted",TripAct(c.status.activity)+(c.status.late?" · retour dépassé":" · retour vers "+TripHm(c.status.returnAt))))))):e("p.small.muted",{style:{margin:0}},"Aucun ami en sortie pour l’instant.")),
k({title:"Confidentialité"},e("div.stack",{style:{gap:"10px"}},e("label.check",cb,e("span","Montrer à mes amis quand je suis en sortie",e("div.hint.muted.small","Ils voient seulement l’activité et l’heure de retour prévue. Jamais votre position ni votre lieu."))),e("p.small.muted",{style:{margin:0}},"Désactivé par défaut. Vos publications gardent leur propre visibilité."))),
k({title:"Bon à savoir"},e("ul.small",{style:{paddingLeft:"18px",margin:0,lineHeight:1.7}},e("li","Une demande doit être acceptée pour devenir ami."),e("li","Vous pouvez retirer un ami à tout moment."),e("li","Le filtre « Amis » du fil n’affiche que vos amis et vous."))))};
C(t,q({title:"Amis",subtitle:"Retrouvez vos partenaires de chasse et de pêche, invitez-les en sortie et suivez leurs publications. Vous décidez de ce qu’ils voient."}),e("div.grid.g-main",e("div.stack",head,body),side));
await reload()}
function FriendBtn(uid){let box=e("span"),draw=async()=>{let r;try{r=await v.get("/friends/relation/"+uid)}catch{return}W(box);let go=async(fn,msg)=>{try{await fn();A(msg,"ok")}catch(er){A(er.message,"err")}draw()};C(box,r.state==="friends"?x("Ami",{icon:"check",kind:"ghost",onClick:async()=>{if(await ve({title:"Retirer cet ami ?",text:"Vous ne verrez plus vos sorties respectives.",confirm:"Retirer",danger:!0}))go(()=>v.del("/friends/user/"+uid),"Ami retiré.")}}):r.state==="sent"?x("Demande envoyée",{kind:"ghost",onClick:()=>go(()=>v.post("/friends/"+r.id+"/decline"),"Demande annulée.")}):r.state==="received"?x("Accepter la demande",{icon:"check",kind:"primary",onClick:()=>go(()=>v.post("/friends/"+r.id+"/accept"),"Vous êtes maintenant amis.")}):x("Ajouter en ami",{icon:"plus",kind:"primary",onClick:()=>go(()=>v.post("/friends/request",{userId:uid}),"Demande envoyée.")}))};draw();return box}
var FriM={};le(FriM,{default:()=>FriendsView});var FriI=H(()=>{});
