/* ===== 3.0 serveur : amis ===== */
function FrDoc(a,b){return se.friendships.find(z=>(z.fromId===a&&z.toId===b)||(z.fromId===b&&z.toId===a))}
function FrIds(uid,withMe){if(!uid)return[];let ids=se.friendships.all(z=>z.status==="accepted"&&(z.fromId===uid||z.toId===uid)).map(z=>z.fromId===uid?z.toId:z.fromId);return withMe?[uid,...ids]:ids}
function FrSeed(){if(window.__frS)return;window.__frS=1;if(se.friendships.count())return;if(!se.users.get("u_marc"))return;let ago=h=>new Date(Date.now()-h*36e5).toISOString(),ok=(a,b,h)=>se.friendships.insert({fromId:a,toId:b,status:"accepted",createdAt:ago(h)});
ok("u_marc","u_sophie",900);ok("u_luc","u_marc",700);ok("u_claire","u_marc",400);ok("u_sophie","u_luc",300);ok("u_paul","u_luc",200);
se.friendships.insert({fromId:"u_paul",toId:"u_marc",status:"pending",createdAt:ago(5)});
let inH=h=>new Date(Date.now()+h*36e5).toISOString();
se.fstatus.insert({userId:"u_sophie",active:!0,activity:"peche",returnAt:inH(2.5),since:ago(1)});
se.fstatus.insert({userId:"u_luc",active:!0,activity:"chasse",returnAt:inH(1.2),since:ago(2)})}
function FrStatus(uid){let s=se.fstatus.find(z=>z.userId===uid);if(!s||!s.active)return null;if(new Date(s.returnAt).getTime()<Date.now()-36e5*3)return null;return{activity:s.activity,returnAt:s.returnAt,since:s.since,late:new Date(s.returnAt).getTime()<Date.now()}}
function FrMutual(a,b){let fb=FrIds(b);return FrIds(a).filter(i=>fb.includes(i)).length}
function FrState(me,uid){let d=FrDoc(me,uid);return!d?"none":d.status==="accepted"?"friends":d.fromId===me?"sent":"received"}
function FrCard(me,uid,extra){let u=se.users.get(uid);if(!u)return null;return{user:_t(u),mutual:FrMutual(me,uid),...extra}}
Be.get("/friends",bt(async(t,r)=>{FrSeed();let me=t.user.id,fr=se.friendships.all(z=>z.status==="accepted"&&(z.fromId===me||z.toId===me)),friends=fr.map(z=>FrCard(me,z.fromId===me?z.toId:z.fromId,{since:z.createdAt,status:FrStatus(z.fromId===me?z.toId:z.fromId)})).filter(Boolean).sort((a,b2)=>(b2.status?1:0)-(a.status?1:0)||a.user.name.localeCompare(b2.user.name)),
received=se.friendships.all(z=>z.status==="pending"&&z.toId===me).map(z=>FrCard(me,z.fromId,{id:z.id,createdAt:z.createdAt})).filter(Boolean),sent=se.friendships.all(z=>z.status==="pending"&&z.fromId===me).map(z=>FrCard(me,z.toId,{id:z.id,createdAt:z.createdAt})).filter(Boolean),
mine=se.users.get(me)||{},sug=se.users.all(u=>u.id!==me&&u.role!=="admin"&&u.role!=="moderator"&&!FrDoc(me,u.id)).map(u=>{let m=FrMutual(me,u.id),same=u.department&&u.department===mine.department;return{user:_t(u),mutual:m,reason:m?m+" ami"+(m>1?"s":"")+" en commun":same?"Près de chez vous · département "+u.department:"",score:m*10+(same?3:0)}}).filter(z=>z.score>0).sort((a,b2)=>b2.score-a.score).slice(0,8);
r.json({friends,received,sent,suggestions:sug,out:friends.filter(z=>z.status).length})}));
Be.get("/friends/search",bt(async(t,r)=>{FrSeed();let me=t.user.id,q1=String(t.query.q||"").trim().toLowerCase();if(q1.length<2)return r.json([]);r.json(se.users.all(u=>u.id!==me&&u.role!=="admin"&&((u.name||"").toLowerCase().includes(q1)||(u.city||"").toLowerCase().includes(q1))).slice(0,20).map(u=>({user:_t(u),state:FrState(me,u.id),mutual:FrMutual(me,u.id)}))) }));
Be.get("/friends/relation/:uid",bt(async(t,r)=>{FrSeed();let d=FrDoc(t.user.id,t.params.uid);r.json({state:FrState(t.user.id,t.params.uid),id:d?d.id:null})}));
Be.post("/friends/request",bt(async(t,r)=>{yr(t.body,{userId:"string"});let me=t.user.id,to=t.body.userId;if(to===me)throw new lt(400,"Vous ne pouvez pas vous ajouter vous-même.");let u=se.users.get(to);if(!u)throw new lt(404,"Membre introuvable.");let d=FrDoc(me,to);if(d){if(d.status==="accepted")throw new lt(400,"Vous êtes déjà amis.");if(d.toId===me){se.friendships.update(d.id,{status:"accepted"});wr(to,"friend",t.user.name+" a accepté votre demande d’ami.","#/amis");return r.json({state:"friends"})}throw new lt(400,"Demande déjà envoyée.")}
if(se.friendships.count(z=>z.fromId===me&&z.status==="pending")>=30)throw new lt(429,"Trop de demandes en attente : patientez avant d’en envoyer d’autres.");
se.friendships.insert({fromId:me,toId:to,status:"pending",createdAt:new Date().toISOString()});wr(to,"friend",t.user.name+" vous a envoyé une demande d’ami.","#/amis");r.status(201).json({state:"sent"})}));
Be.post("/friends/:id/accept",bt(async(t,r)=>{let d=se.friendships.get(t.params.id);if(!d||d.toId!==t.user.id||d.status!=="pending")throw new lt(404,"Demande introuvable.");se.friendships.update(d.id,{status:"accepted"});wr(d.fromId,"friend",t.user.name+" a accepté votre demande d’ami.","#/amis");r.json({ok:!0})}));
Be.post("/friends/:id/decline",bt(async(t,r)=>{let d=se.friendships.get(t.params.id);if(!d||d.status!=="pending"||(d.toId!==t.user.id&&d.fromId!==t.user.id))throw new lt(404,"Demande introuvable.");se.friendships.remove(d.id);r.json({ok:!0})}));
Be.delete("/friends/user/:uid",bt(async(t,r)=>{let d=FrDoc(t.user.id,t.params.uid);if(!d)throw new lt(404,"Relation introuvable.");se.friendships.remove(d.id);r.json({ok:!0})}));
Be.post("/friends/status",bt(async(t,r)=>{let b0=t.body||{},cur=se.fstatus.find(z=>z.userId===t.user.id),act=["chasse","peche","nature"].includes(b0.activity)?b0.activity:"chasse",rt=b0.returnAt&&!isNaN(new Date(b0.returnAt))?new Date(b0.returnAt).toISOString():null,doc={userId:t.user.id,active:!!b0.active&&!!rt,activity:act,returnAt:rt,since:new Date().toISOString()};if(cur)se.fstatus.update(cur.id,doc);else se.fstatus.insert(doc);r.json({ok:!0})}));
