/* ===== 3.0 : historique des sorties (déroulé, tracé, publication) ===== */
function HDur(ms){let m=Math.max(0,Math.round(ms/6e4)),h=Math.floor(m/60);return h?h+" h "+String(m%60).padStart(2,"0"):m+" min"}
function HDist(tr){let a=tr.track||[],d=0;for(let i=1;i<a.length;i++)d+=HavM({lat:a[i-1][0],lng:a[i-1][1]},{lat:a[i][0],lng:a[i][1]});return d}
function HKm(m){return m<950?Math.round(m)+" m":(m/1e3).toFixed(1).replace(".",",")+" km"}
function HSummary(tr){let d=HDur(new Date(tr.endedAt)-new Date(tr.start)),dist=HDist(tr);return"Sortie "+TripAct(tr.activity)+(tr.kind?" ("+String(tr.kind).toLowerCase()+")":"")+" de "+TripHm(tr.start)+" à "+TripHm(tr.endedAt)+" : "+d+(dist>50?", "+HKm(dist)+" parcourus":"")+"."+(tr.note?" "+tr.note:"")}
function HRoute(tr,trim){let a=(tr.track||[]).filter(p=>isFinite(p[0])&&isFinite(p[1])).map(p=>[p[0],p[1]]);if(trim&&a.length){let s0=a[0],e0=a[a.length-1],far=(p,o)=>HavM({lat:p[0],lng:p[1]},{lat:o[0],lng:o[1]})>250;a=a.filter(p=>far(p,s0)&&far(p,e0))}if(a.length<2)return null;let st=Math.max(1,Math.ceil(a.length/80));return a.filter((p,i)=>i%st===0||i===a.length-1).map(p=>[+p[0].toFixed(4),+p[1].toFixed(4)])}
function HShape(tr,rt){let a=rt||[];if(a.length<3)return null;let la=a.reduce((s,p)=>s+p[0],0)/a.length,kk=Math.cos(la*Math.PI/180),pts=a.map(p=>[p[1]*kk,-p[0]]),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),x0=Math.min(...xs),y0=Math.min(...ys),sc=Math.max(Math.max(...xs)-x0,Math.max(...ys)-y0)||1,st=Math.max(1,Math.ceil(pts.length/60));return pts.filter((p,i)=>i%st===0||i===pts.length-1).map(p=>[+((p[0]-x0)/sc*88+6).toFixed(1),+((p[1]-y0)/sc*88+6).toFixed(1)])}
function TripAttach(u){let nn=z=>isFinite(+z)?+z:0,sh=(Array.isArray(u.shape)?u.shape.slice(0,80):[]).filter(Array.isArray).map(p=>[nn(p[0]),nn(p[1])]),pe=u.activity==="peche",ico,
rt=(Array.isArray(u.route)?u.route.slice(0,100):[]).filter(p=>Array.isArray(p)&&isFinite(+p[0])&&isFinite(+p[1])&&Math.abs(+p[0])<=90&&Math.abs(+p[1])<=180).map(p=>[+p[0],+p[1]]),mapEl=null;
if(!rt.length&&sh.length>1){ico=ChSvg('<svg viewBox="0 0 100 100" width="84" height="84" role="img" aria-label="Forme du parcours" style="flex:none;background:var(--surface-2,#ECE8DE);border-radius:14px"><polyline points="'+sh.map(p=>p.join(",")).join(" ")+'" fill="none" stroke="#D95A10" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"/></svg>')}
if(rt.length>1){mapEl=e("div",{style:{height:"210px",borderRadius:"14px",overflow:"hidden",marginTop:"10px",background:"#E8E4DA"},role:"img","aria-label":"Carte du parcours"});let tries=0,init=()=>{if(!mapEl.isConnected){tries++<40&&setTimeout(init,100);return}try{let m=De(mapEl,{center:{lat:rt[0][0],lng:rt[0][1]},zoom:14,controls:!1});["dragging","scrollWheelZoom","touchZoom","doubleClickZoom","boxZoom","keyboard"].forEach(k1=>{try{m[k1].disable()}catch{}});let L1=Ve();L1.polyline(rt,{color:"#D95A10",weight:4,opacity:.95}).addTo(m);at(m,rt,{padding:[24,24]})}catch{}};setTimeout(init,0)}
let info=[nn(u.durationMin)?HDur(nn(u.durationMin)*6e4):null,nn(u.distanceKm)?String(nn(u.distanceKm)).replace(".",",")+" km":null,typeof u.tripKind==="string"?u.tripKind.slice(0,40):null].filter(Boolean).join(" · ");
return e("div",{style:{marginTop:"10px",padding:"10px",border:"1px solid var(--line,#DDD8CC)",borderRadius:"16px"}},e("div",{style:{display:"flex",alignItems:"center",gap:"12px"}},ico||null,e("div",{style:{flexGrow:1,minWidth:0}},e("b",{style:{fontSize:"18px"}},"Sortie "+(pe?"pêche":"chasse")),e("div.small.muted",info||"Journal de sortie")),L("Journal de sortie","accent")),mapEl)}
async function HistList(t,pa){
let act=pa&&pa.act==="peche"?"peche":pa&&pa.act==="chasse"?"chasse":"tous",u=w.user,all=Pe.get("trips-hist:"+u.id,[]),ls=all.filter(z=>act==="tous"||z.activity===act||z.activity==="nature"),
tot=ls.reduce((s,z)=>s+(new Date(z.endedAt)-new Date(z.start)),0),dist=ls.reduce((s,z)=>s+HDist(z),0),
title=act==="peche"?"Historique des sorties pêche":act==="chasse"?"Historique des sorties chasse":"Historique des sorties",
acts=act==="tous"?[]:[x("Nouvelle sortie",{icon:"plus",kind:"primary",href:"#/sortie/"+act})],
kp=e("div.grid.g-3",k({},ee(String(ls.length),"Sorties terminées")),k({},ee(ls.length?HDur(tot):"—","Temps passé dehors")),k({},ee(dist>50?HKm(dist):"—","Distance enregistrée"))),
cards=ls.map(z=>{let sub=M.dateTime(z.start)+" → "+TripHm(z.endedAt)+" · "+HDur(new Date(z.endedAt)-new Date(z.start))+(HDist(z)>50?" · "+HKm(HDist(z)):"");
return e("a.panel",{href:"#/sortie-detail/"+z.id,style:{display:"block",padding:"16px",textDecoration:"none",color:"inherit"}},e("div.pill-row",L(TripAct(z.activity),"accent"),z.kind?L(z.kind):null,z.publishedId?L("Publiée","ok"):L("Privée")),e("h3.display",{style:{margin:"8px 0 2px",fontSize:"22px"}},z.place||"Sortie "+TripAct(z.activity)),e("div.small.muted",sub))}),
body=ls.length?e("div.grid.g-2",{style:{marginTop:"18px"}},cards):e("div",{style:{marginTop:"18px"}},V({icon:"clock",title:"Aucune sortie enregistrée",text:"Démarrez une sortie : à votre retour, son déroulé apparaît ici.",action:act==="tous"?null:x("Démarrer une sortie",{kind:"primary",icon:"play",href:"#/sortie/"+act})}));
C(t,q({title:title,subtitle:"Le déroulé de chacune de vos sorties : départ, prolongations, alertes, retour et tracé. Vous décidez de ce qui est publié.",actions:acts}),kp,body)}
async function HistDetail(t,pa){
let u=w.user,key="trips-hist:"+u.id,all=Pe.get(key,[]),tr=all.find(z=>z.id===(pa&&pa.id)),map0=null;
if(!tr){C(t,q({title:"Sortie introuvable"}),V({icon:"alert",title:"Cette sortie n’existe plus sur cet appareil",text:"L’historique est conservé sur l’appareil où la sortie a été enregistrée.",action:x("Historique",{href:"#/historique/tous",kind:"primary"})}));return}
let back="#/historique/"+(tr.activity==="peche"?"peche":"chasse"),save=()=>Pe.set(key,all),dur=new Date(tr.endedAt)-new Date(tr.start),dist=HDist(tr),late=new Date(tr.endedAt)-new Date(tr.returnAt),
ext=(tr.events||[]).filter(z=>z.type==="extend").length,pts=(tr.track||[]).filter(p=>isFinite(p[0])&&isFinite(p[1])),
mapEl=e("div.map",{style:{height:"340px"}}),pub=e("div"),
note=e("textarea",{placeholder:"Ce qui s’est passé, ce que vous avez vu, vos conditions…",style:{minHeight:"110px",width:"100%"},maxlength:600}),
tl=(tr.events||[]).slice().sort((a,b)=>String(a.t).localeCompare(String(b.t))),rpub,publish;
publish=async()=>{let hasTrack=pts.length>2,ok=await Q({title:"Publier cette sortie",intro:"Cette publication sera visible de tous dans le fil. Choisissez ce qu’elle montre.",submit:"Publier au fil",
fields:[{name:"text",label:"Texte",type:"textarea",required:!0,value:HSummary(tr)},{name:"place",label:"Lieu affiché (facultatif)",placeholder:"Sologne, Loir-et-Cher…"},{name:"stats",type:"checkbox",label:"Afficher la durée et la distance",value:!0},{name:"visual",label:"Visuel du parcours",type:"select",value:hasTrack?"map":"none",options:hasTrack?[{value:"map",label:"Carte du parcours"},{value:"shape",label:"Forme seule (sans carte)"},{value:"none",label:"Aucun visuel"}]:[{value:"none",label:"Aucun (pas de tracé enregistré)"}]},{name:"trim",type:"checkbox",label:"Masquer 250 m autour du départ et de l’arrivée (recommandé)",value:!0}],
onSubmit:async d=>{let act=tr.activity==="peche"?"peche":"chasse",a2={kind:"trip",activity:act};if(d.stats){a2.durationMin=Math.round(dur/6e4);if(dist>50)a2.distanceKm=+(dist/1e3).toFixed(1)}if(tr.kind)a2.tripKind=String(tr.kind).slice(0,40);if(d.visual==="map"||d.visual==="shape"){let rt=HRoute(tr,!!d.trim);if(!rt)throw new Error("Parcours trop court pour être publié avec cette protection : décochez le masquage ou choisissez « Aucun visuel ».");if(d.visual==="map")a2.route=rt;else{let sh=HShape(tr,rt);if(!sh)throw new Error("Parcours trop court pour dessiner une forme.");a2.shape=sh}}
let post=await v.post("/feed",{text:String(d.text||"").slice(0,1500),activity:act,place:String(d.place||"").slice(0,60),attachment:a2});tr.publishedId=post&&post.id||"pub";save()}});
if(ok){A("Sortie publiée au fil.","ok");rpub()}};
rpub=()=>{W(pub);C(pub,tr.publishedId?e("div.stack",{style:{gap:"10px"}},L("Publiée au fil d’actualité","ok"),e("div",{style:{display:"flex",gap:"8px",flexWrap:"wrap"}},x("Voir le fil",{href:"#/communaute",size:"sm"}),x("Retirer du fil",{kind:"ghost",size:"sm",icon:"trash",onClick:async()=>{try{await v.del("/feed/"+tr.publishedId)}catch{}tr.publishedId=null;save();A("Retirée du fil.");rpub()}}))):e("div.stack",{style:{gap:"10px"}},e("p.small.muted",{style:{margin:0}},"Cette sortie est privée. Vous pouvez en publier un récit, avec ou sans carte du parcours : le départ et l’arrivée sont masqués par défaut."),x("Publier cette sortie",{icon:"send",kind:"primary",onClick:publish})))};
rpub();note.value=tr.report||"";
let kp=e("div.grid.g-4",k({},ee(HDur(dur),"Durée")),k({},ee(dist>50?HKm(dist):"—","Distance",{delta:pts.length>1?pts.length+" points GPS":"pas de tracé"})),k({},ee(TripHm(tr.endedAt),"Retour",{delta:late>3e5?"+"+HDur(late)+" après l’heure prévue":"dans les temps",deltaTone:late>3e5?"warn":"ok"})),k({},ee(String(ext),"Prolongation"+(ext>1?"s":"")))),
mapPanel=k({title:"Tracé",flush:!0},pts.length>1?mapEl:e("p.small.muted",{style:{padding:"16px",margin:0}},"Aucun tracé enregistré : la position précise n’était pas disponible. Sur la version hébergée (https) avec la localisation activée, le parcours est relevé pendant la sortie.")),
tlPanel=k({title:"Déroulé"},tl.length?e("div.stack",{style:{gap:"10px"}},tl.map(z=>e("div",{style:{display:"flex",gap:"12px",alignItems:"baseline"}},e("b",{style:{minWidth:"48px"}},TripHm(z.t)),e("span",{style:{color:z.type==="late"||z.type==="alert"?"#D2513F":"inherit"}},z.label)))):e("p.small.muted",{style:{margin:0}},"Aucun événement enregistré.")),
notePanel=k({title:"Compte rendu"},e("div.stack",{style:{gap:"10px"}},note,x("Enregistrer",{size:"sm",icon:"check",onClick:()=>{tr.report=note.value.trim().slice(0,600);tr.note=tr.report;save();A("Compte rendu enregistré.","ok")}}))),
pubPanel=k({title:"Publication"},pub),
expPanel=k({title:"Exporter"},e("div.stack",{style:{gap:"8px"}},x("Copier le récit",{icon:"file",size:"sm",onClick:async()=>{let txt=HSummary(tr)+"\n\n"+tl.map(z=>TripHm(z.t)+" "+z.label).join("\n");try{await navigator.clipboard.writeText(txt);A("Récit copié.","ok")}catch{A("Copie impossible ici.","warn")}}}),pts.length>1?x("Tracé GPX",{icon:"download",size:"sm",onClick:()=>{if(!HasF("territory.export")){A("L’export GPX fait partie des offres Premium.","warn");return}let f={name:"sortie-"+tr.id+".gpx",mime:"application/gpx+xml",text:'<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Chasse et Pêche 360" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>'+TXml(HSummary(tr).slice(0,80))+"</name><trkseg>"+pts.map(p=>'<trkpt lat="'+p[0]+'" lon="'+p[1]+'"><time>'+new Date(p[2]).toISOString()+"</time></trkpt>").join("")+"</trkseg></trk></gpx>"};TDownload(f)?A("Fichier préparé.","ok"):A("Téléchargement indisponible ici.","warn")}}):null)),
delPanel=k({},x("Supprimer cette sortie",{icon:"trash",kind:"ghost",size:"sm",onClick:async()=>{if(await ve({title:"Supprimer cette sortie ?",text:"Son déroulé sera effacé de cet appareil."+(tr.publishedId?" Sa publication au fil sera aussi retirée.":""),confirm:"Supprimer",danger:!0})){if(tr.publishedId)try{await v.del("/feed/"+tr.publishedId)}catch{}Pe.set(key,all.filter(z=>z.id!==tr.id));A("Sortie supprimée.");location.hash=back}}}));
C(t,q({title:"Sortie "+TripAct(tr.activity)+(tr.place?" · "+tr.place:""),subtitle:M.dateTime(tr.start)+" → "+TripHm(tr.endedAt),actions:[x("Historique",{icon:"back",kind:"ghost",href:back})]}),kp,e("div.grid.g-main",{style:{marginTop:"18px"}},e("div.stack",mapPanel,tlPanel),e("div.stack",notePanel,pubPanel,expPanel,delPanel)));
if(pts.length>1)try{let ll=pts.map(p=>[p[0],p[1]]),m=De(mapEl,{center:{lat:ll[0][0],lng:ll[0][1]},zoom:15}),L1=Ve();L1.polyline(ll,{color:"#D95A10",weight:4,opacity:.9}).addTo(m);L1.circleMarker(ll[0],{radius:8,color:"#fff",weight:2,fillColor:"#2F7A4C",fillOpacity:1}).addTo(m);L1.circleMarker(ll[ll.length-1],{radius:8,color:"#fff",weight:2,fillColor:"#D2513F",fillOpacity:1}).addTo(m);at(m,ll,{padding:[30,30]});map0=m}catch{}
return()=>{try{map0&&map0.remove()}catch{}}}
var HisM={};le(HisM,{default:()=>HistList});var HisI=H(()=>{});
var HidM={};le(HidM,{default:()=>HistDetail});var HidI=H(()=>{});
