/* ===== 3.0 : suivi en direct ===== */
var __lvLast="",__lvPos=0;
function LiveIds(t){return t&&t.status==="active"&&t.live&&t.live.on?(t.live.ids||[]):[]}
function LiveSync(t){if(!w.user)return;let ids=LiveIds(t),body=ids.length?{active:!0,allowed:ids,activity:t.activity,returnAt:t.returnAt}:{active:!1},k1=JSON.stringify(body);if(k1===__lvLast)return;__lvLast=k1;try{v.post("/live/session",body).catch(()=>{})}catch{}}
function LivePush(t,p){if(!LiveIds(t).length||Date.now()-__lvPos<8000)return;__lvPos=Date.now();try{v.post("/live/position",{lat:p.lat,lng:p.lng}).catch(()=>{})}catch{}}
function LiveAgo(iso){let s=Math.max(0,Math.round((Date.now()-new Date(iso))/1000));return s<45?"à l’instant":s<3600?"il y a "+Math.max(1,Math.round(s/60))+" min":"il y a "+Math.round(s/3600)+" h"}
function LivePanel(cur,re){let box=e("div.stack",{style:{gap:"10px"}}),panel=k({title:"Suivi en direct",sub:"Seulement les personnes que vous autorisez"},box),u=w.user,ok=w.position&&!w.position.approx;
(async()=>{let fr=[];try{fr=(await v.get("/friends")).friends}catch{}
if(cur.live&&cur.live.on){let n=(cur.live.ids||[]).length;C(box,e("div",L("Actif · "+n+" personne"+(n>1?"s":""),"ok")),e("p.small.muted",{style:{margin:0}},ok?"Elles voient votre position sur la carte jusqu’à la fin de la sortie. Vous pouvez arrêter à tout moment.":"Actif, mais la position précise est indisponible ici : rien n’est envoyé tant que la localisation n’est pas activée (version hébergée, en https)."),e("div",{style:{display:"flex",gap:"8px",flexWrap:"wrap"}},x("Voir la carte",{href:"#/suivi",size:"sm"}),x("Arrêter le suivi",{kind:"ghost",size:"sm",onClick:()=>{cur.live={on:!1,ids:[]};TripEv(cur,"live","Suivi en direct arrêté");TripSet(cur);A("Suivi en direct arrêté.");re()}})));return}
if(!fr.length){C(box,e("p.small.muted",{style:{margin:0}},"Ajoutez des amis pour leur permettre de suivre votre sortie sur une carte, en temps réel."),x("Trouver des amis",{href:"#/amis",size:"sm"}));return}
let saved=Pe.get("live-ids:"+u.id,[]),cbs=fr.map(c=>{let cb=e("input",{type:"checkbox",checked:saved.includes(c.user.id)});return{c,cb}});
C(box,e("p.small.muted",{style:{margin:0}},"Choisissez qui peut voir votre position pendant cette sortie. Le partage s’arrête tout seul quand vous rentrez."),e("div.stack",{style:{gap:"8px"}},cbs.map(z=>e("label.check",z.cb,e("span",z.c.user.name)))),x("Activer le suivi en direct",{icon:"locate",kind:"primary",size:"block",onClick:()=>{let ids=cbs.filter(z=>z.cb.checked).map(z=>z.c.user.id);if(!ids.length){A("Cochez au moins une personne.","warn");return}Pe.set("live-ids:"+u.id,ids);cur.live={on:!0,ids:ids};TripEv(cur,"live","Suivi en direct activé pour "+ids.length+" personne"+(ids.length>1?"s":""));TripSample();TripSet(cur);A("Suivi en direct activé.","ok");re()}}),ok?null:e("p.small.muted",{style:{margin:0}},"Position précise indisponible ici : sur la version hébergée (https) avec la localisation activée, votre position est envoyée pendant la sortie."))})();return panel}
async function LiveView(t){
let mapEl=e("div.map",{style:{height:"min(60vh,520px)",minHeight:"320px"}}),list=e("div.stack"),mine=e("div"),m=null,lg=null,timer=null,first=!0,data={sessions:[],mine:null},COL={chasse:"#D95A10",peche:"#2E687D",nature:"#4F7A5E"};
let focus=s=>{if(!m||!s.last)return;try{m.setView([s.last[0],s.last[1]],16)}catch{}},
paint=()=>{W(list);W(mine);
C(mine,data.mine?k({title:"Mon partage"},e("p.small",{style:{margin:"0 0 10px"}},"Vous partagez votre sortie avec "+data.mine.count+" personne"+(data.mine.count>1?"s":"")+"."),x("Gérer",{size:"sm",href:"#/sortie/"+(w.season==="peche"?"peche":"chasse")})):k({title:"Mon partage"},e("p.small.muted",{style:{margin:"0 0 10px"}},"Vous ne partagez pas votre position. Démarrez une sortie puis activez le suivi en direct pour les amis de votre choix."),x("Démarrer une sortie",{size:"sm",kind:"primary",href:"#/sortie/"+(w.season==="peche"?"peche":"chasse")})));
if(!data.sessions.length){C(list,V({icon:"locate",title:"Personne ne partage sa sortie avec vous",text:"Quand un ami active le suivi en direct pour vous, il apparaît ici sur la carte avec son trajet."}));return}
data.sessions.forEach(s=>C(list,e("div.panel",{style:{padding:"14px"}},e("div",{style:{display:"flex",gap:"12px",alignItems:"center",flexWrap:"wrap"}},oe(s.user,44),e("div",{style:{flex:"1 1 150px",minWidth:0}},e("b",s.user.name),e("div.small.muted",TripAct(s.activity)+" · retour prévu "+TripHm(s.returnAt)),e("div.small.muted",s.last?"Position "+LiveAgo(s.updatedAt):"Position pas encore reçue"),e("div.pill-row",{style:{marginTop:"6px"}},s.late?L("Retour dépassé","warn"):null,s.demo?L("Simulation de démonstration"):null)),e("div",{style:{display:"flex",gap:"8px"}},x("Centrer",{size:"sm",icon:"locate",onClick:()=>focus(s)}),x("Message",{size:"sm",icon:"chat",onClick:async()=>{let c=await v.post("/conversations",{memberIds:[s.user.id]});ge("/messages/"+c.id)}}))))))},
refresh=async()=>{try{data=await v.get("/live")}catch{return}paint();if(!m)return;try{lg.clearLayers();let L1=Ve(),all=[];data.sessions.forEach(s=>{let col=COL[s.activity]||COL.chasse,tr=(s.track||[]).map(p=>[p[0],p[1]]);if(tr.length>1)L1.polyline(tr,{color:col,weight:4,opacity:.85}).addTo(lg);if(s.last){let ll=[s.last[0],s.last[1]];all.push(ll);L1.circleMarker(ll,{radius:10,color:"#fff",weight:3,fillColor:s.late?"#D2513F":col,fillOpacity:1}).bindTooltip(s.user.name+" · retour "+TripHm(s.returnAt),{permanent:!0,direction:"top",offset:[0,-8]}).addTo(lg)}});if(first&&all.length){first=!1;at(m,all.length>1?all:[all[0],all[0]],{maxZoom:15})}}catch{}};
C(t,q({title:"Suivi en direct",subtitle:"Les amis qui partagent leur sortie avec vous, en temps réel. Chacun choisit qui voit sa position et peut arrêter à tout moment."}),e("div.grid.g-main",e("div.stack",k({flush:!0},mapEl),e("p.small.muted",{style:{margin:0}},"La carte se rafraîchit toute seule toutes les 10 secondes.")),e("div.stack",mine,list)));
try{m=De(mapEl,{center:w.position||{lat:47.6445,lng:2.181},zoom:12});lg=Ve().layerGroup().addTo(m)}catch{m=null}
await refresh();timer=setInterval(refresh,1e4);
return()=>{clearInterval(timer);try{m&&m.remove()}catch{}}}
var LivM={};le(LivM,{default:()=>LiveView});var LivI=H(()=>{});
