/* ===== Mentions d'usage : carnet personnel, permis, données personnelles ===== */
function LegalOpen(){let sec=(t,...b)=>e("div",{style:{marginTop:"14px"}},e("div.tiny.muted",{style:{fontWeight:"700",textTransform:"uppercase",letterSpacing:".5px"}},t),...b),p=t=>e("p.small",{style:{margin:"4px 0 0",lineHeight:"1.55"}},t);
Le({title:"Cadre d’usage et données personnelles",wide:!0,body:e("div.stack",{style:{gap:"0"}},
sec("Un carnet personnel, pas un document officiel",p("Chasse & Pêche 360° est un outil de consultation et de suivi personnels : journal de sorties, statistiques, repérage, notes. Il ne remplace aucun document officiel.")),
sec("Sur le terrain",p("Lors d’un contrôle (OFB, garde champêtre, gendarmerie…), une photo, un scan ou une fiche affichée dans l’application n’est pas un justificatif. Il faut présenter le permis de chasser original et la validation de la saison en cours, ainsi que les autres documents exigés (assurance, carte de pêche…). Pensez à les emporter.")),
sec("Prélèvements soumis à déclaration",p("Pour les espèces soumises à un prélèvement maximal autorisé (PMA) ou à la gestion adaptative (par exemple la bécasse des bois et certains oiseaux d’eau), le prélèvement doit être déclaré via ChassAdapt ou sur le carnet papier délivré par votre fédération. Le tableau de chasse de l’application n’a, pour ces espèces, aucune valeur juridique. Même chose pour les captures soumises à déclaration en pêche (anguille, saumon…) : suivez la procédure officielle.")),
sec("Vos données",p("Le numéro de permis est une donnée personnelle : ne le saisissez que si vous le souhaitez, et n’ajoutez ni scan ni photo de pièce d’identité. Il n’est pas partagé avec les autres membres. Dans cette version de démonstration, vos données restent sur cet appareil. Avant un lancement public, il faudra des conditions d’utilisation, une politique de confidentialité conforme au RGPD et le chiffrement des données : ces textes doivent être validés par un juriste.")),
e("div.tiny.muted",{style:{marginTop:"16px"}},"Les textes officiels (code de l’environnement, arrêtés, fédération) font foi.")
)})}
function LegalNote(kind){let tx={permis:"Cet espace est un aide-mémoire personnel : il ne remplace pas le permis original ni la validation de la saison, à présenter lors d’un contrôle. Ne saisissez que le numéro, sans scan ni photo de pièce.",bag:"Carnet personnel, sans valeur légale. Pour les espèces soumises à PMA ou à la gestion adaptative (bécasse des bois, certains oiseaux d’eau…), déclarez vos prélèvements via ChassAdapt ou le carnet papier de votre fédération."}[kind];
return e("div.panel.tint",{style:{marginTop:"14px",padding:"12px 14px"}},e("div.row",{style:{alignItems:"flex-start",gap:"10px"}},b("shield"),e("div.grow",e("div.small",{style:{lineHeight:"1.5"}},tx),e("a.link-more",{href:"#",style:{display:"inline-block",marginTop:"6px"},onclick:ev=>{ev.preventDefault(),LegalOpen()}},"Cadre d’usage et données personnelles"))))}
