/* ===== 3.0 serveur : suivi en direct (personnes autorisées) ===== */
function LvDist(a,b){let R=6371008.8,k=Math.PI/180,dl=(b[0]-a[0])*k,dn=(b[1]-a[1])*k,x1=Math.sin(dl/2)**2+Math.cos(a[0]*k)*Math.cos(b[0]*k)*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(x1))}
function LvDemo(uid){let C0={u_luc:[47.6103,2.0189,"chasse"],u_sophie:[47.5906,1.3420,"peche"]}[uid];if(!C0)return null;let st=se.fstatus.find(z=>z.userId===uid);if(!st||!st.active)return null;let th=Date.now()/9e4%(2*Math.PI),rad=C0[2]==="peche"?.0035:.007,pt=a=>[+(C0[0]+Math.sin(a)*rad*.8+Math.sin(a*3)*.0008).toFixed(5),+(C0[1]+Math.cos(a)*rad*1.2).toFixed(5)],tr=[];for(let i=34;i>=0;i--)tr.push([...pt(th-i*.09),Date.now()-i*45e3]);return{track:tr,last:tr[tr.length-1],updatedAt:new Date().toISOString(),activity:st.activity,returnAt:st.returnAt,demo:!0}}
Be.post("/live/session",bt(async(t,r)=>{let me=t.user.id,b0=t.body||{},cur=se.livesessions.find(z=>z.userId===me),fr=FrIds(me),allowed=(Array.isArray(b0.allowed)?b0.allowed:[]).filter(i=>typeof i==="string"&&fr.includes(i)).slice(0,30),rt=b0.returnAt&&!isNaN(new Date(b0.returnAt))?new Date(b0.returnAt).toISOString():null,on=!!b0.active&&allowed.length>0&&!!rt,act=["chasse","peche","nature"].includes(b0.activity)?b0.activity:"chasse",prev=cur&&cur.active?cur.allowed:[];
let doc={userId:me,active:on,allowed:on?allowed:[],activity:act,returnAt:rt,points:on&&cur&&cur.active?cur.points:[],updatedAt:new Date().toISOString(),startedAt:on&&cur&&cur.active?cur.startedAt:new Date().toISOString()};if(cur)se.livesessions.update(cur.id,doc);else se.livesessions.insert(doc);
if(on)allowed.filter(i=>!prev.includes(i)).forEach(i=>wr(i,"live",t.user.name+" partage sa sortie en direct avec vous.","#/suivi"));r.json({ok:!0,active:on,count:doc.allowed.length})}));
Be.post("/live/position",bt(async(t,r)=>{let cur=se.livesessions.find(z=>z.userId===t.user.id);if(!cur||!cur.active)return r.json({ok:!1});let la=+t.body.lat,ln=+t.body.lng;if(!isFinite(la)||!isFinite(ln)||Math.abs(la)>90||Math.abs(ln)>180)throw new lt(400,"Position invalide.");let pts=cur.points||[],l=pts[pts.length-1],p=[+la.toFixed(5),+ln.toFixed(5),Date.now()];if(!l||LvDist(l,p)>10)pts=[...pts,p].slice(-400);else pts=[...pts.slice(0,-1),[l[0],l[1],p[2]]];se.livesessions.update(cur.id,{points:pts,updatedAt:new Date().toISOString()});r.json({ok:!0})}));
Be.get("/live",bt(async(t,r)=>{FrSeed();let me=t.user.id,now=Date.now(),down=a=>{let st=Math.max(1,Math.ceil(a.length/150));return a.filter((p,i)=>i%st===0||i===a.length-1)},out=[];
se.livesessions.all(z=>z.active&&z.allowed.includes(me)&&now-new Date(z.updatedAt)<12*36e5).forEach(z=>{let u=se.users.get(z.userId);if(!u)return;let pts=z.points||[];out.push({user:_t(u),activity:z.activity,returnAt:z.returnAt,late:new Date(z.returnAt)<now,updatedAt:z.updatedAt,last:pts.length?pts[pts.length-1]:null,track:down(pts),demo:!1})});
if(me==="u_marc")FrIds(me).forEach(i=>{if(out.some(o=>o.user.id===i))return;let d=LvDemo(i),u=se.users.get(i);if(d&&u)out.push({user:_t(u),activity:d.activity,returnAt:d.returnAt,late:new Date(d.returnAt)<now,updatedAt:d.updatedAt,last:d.last,track:d.track,demo:!0})});
let mine=se.livesessions.find(z=>z.userId===me);r.json({sessions:out,mine:mine&&mine.active?{count:mine.allowed.length,since:mine.startedAt}:null})}));
