/* ===== 3.0 : messagerie refondue ===== */
function MsgAgo(iso){if(!iso)return"";let d=new Date(iso),n=new Date(),sd=(a,b)=>a.toDateString()===b.toDateString(),y=new Date(n-864e5);if(sd(d,n))return String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0");if(sd(d,y))return"Hier";let df=(n-d)/864e5;if(df<7)return["dim.","lun.","mar.","mer.","jeu.","ven.","sam."][d.getDay()];return String(d.getDate()).padStart(2,"0")+"/"+String(d.getMonth()+1).padStart(2,"0")}
function MsgLink(text){let out=[],re=/(https?:\/\/[^\s<>"']+)/g,last=0,m;text=String(text||"");while((m=re.exec(text))){if(m.index>last)out.push(text.slice(last,m.index));let u=m[1].replace(/[.,;:!?)]+$/,"");out.push(e("a",{href:u,target:"_blank",rel:"noopener noreferrer"},u));last=m.index+u.length;re.lastIndex=last}if(last<text.length)out.push(text.slice(last));return out}
function MsgAvatar(c,s){return c.type==="group"?e("span.avatar",{style:{width:s+"px",height:s+"px",background:"var(--surface-3)",color:"var(--text-2)"}},b("users")):oe(c.others&&c.others[0]||{name:c.name},s)}
async function MsgNew(){let sel=new Map,fr=[],cur=[];try{fr=(await v.get("/friends")).friends.map(c=>c.user)}catch{}cur=fr;
let box=e("div.list",{style:{maxHeight:"300px",overflowY:"auto"}}),chips=e("div.chips"),gname=e("input.input",{placeholder:"Nom du groupe (si plusieurs personnes)"}),gwrap=e("div",{hidden:!0},gname),title=e("div.tiny.muted",{style:{fontWeight:700}},fr.length?"Mes amis":"Résultats"),
drawChips=()=>{B(chips,[...sel.values()].map(P=>e("button.chip",{type:"button","aria-pressed":"true",onclick:()=>{sel.delete(P.id);drawChips();show(cur)}},P.name," ×")));gwrap.hidden=sel.size<2},
show=us=>{cur=us;B(box,us.length?us.map(y=>e("button.list-row",{type:"button",onclick:()=>{sel.has(y.id)?sel.delete(y.id):sel.set(y.id,y);drawChips();show(cur)}},oe(y,36),e("div.grow",e("div.t",y.name),e("div.s",[y.city].filter(Boolean).join(" · "))),sel.has(y.id)?b("check"):b("plus"))):e("p.muted.small",{style:{padding:"8px",margin:0}},"Aucun résultat."))},
find=En(async q1=>{if(!q1.trim()){title.textContent=fr.length?"Mes amis":"Résultats";show(fr);return}title.textContent="Résultats";try{show(await v.get("/auth/users?q="+encodeURIComponent(q1)))}catch{show([])}},220);show(fr);
let M1=Le({title:"Nouvelle conversation",body:e("div.stack",xt("Rechercher par nom ou commune",find),chips,title,box,gwrap),actions:[x("Annuler",{kind:"ghost",onClick:()=>M1.close()}),x("Démarrer",{kind:"primary",onClick:async()=>{if(!sel.size){A("Choisissez au moins une personne.","warn");return}try{let P=await v.post("/conversations",{memberIds:[...sel.keys()],name:sel.size>1?gname.value||"Groupe":void 0});M1.close();ge("/messages/"+P.id)}catch(er){A(er.message,"err")}}})]})}
function MsgKb(root){let vv=window.visualViewport,mq=window.matchMedia("(max-width: 760px)"),de=document.documentElement,off=()=>{root.classList.remove("kb-open");root.style.top="";root.style.height="";de.classList.remove("kb-lock")},
apply=()=>{if(!vv||!mq.matches||!root.classList.contains("has-thread")){off();return}let open=window.innerHeight-vv.height>120;if(!open){off();return}root.classList.add("kb-open");root.style.top=Math.max(0,vv.offsetTop)+"px";root.style.height=vv.height+"px";de.classList.add("kb-lock");let m=root.querySelector(".chat-msgs");m&&(m.scrollTop=m.scrollHeight)};
if(vv){vv.addEventListener("resize",apply);vv.addEventListener("scroll",apply)}window.addEventListener("orientationchange",apply);apply();
return()=>{if(vv){vv.removeEventListener("resize",apply);vv.removeEventListener("scroll",apply)}window.removeEventListener("orientationchange",apply);off();de.classList.remove("chat-focus")}}
async function MsgView(t,pa){
let r=pa&&pa.id,u=w.user,convs=await v.get("/conversations"),flt="",items=e("div.chat-items"),sInp=e("input.input",{type:"search",placeholder:"Rechercher une conversation","aria-label":"Rechercher une conversation",oninput:ev=>{flt=ev.target.value.trim().toLowerCase();drawList()}}),
list=e("div.chat-list",e("div.chat-list-head",x("Nouvelle conversation",{icon:"plus",kind:"primary",size:"block",onClick:MsgNew}),convs.length>4?sInp:null),items),thread=e("div.chat-thread"),root=e("div.chat",{class:r?"has-thread":""},list,thread),typT=null,lastTy=0,api=null;
function drawList(){let ls=convs.slice().sort((a,b2)=>String(b2.lastMessageAt||"").localeCompare(String(a.lastMessageAt||""))).filter(c=>!flt||String(c.name).toLowerCase().includes(flt)||(c.members||[]).some(m=>String(m.name).toLowerCase().includes(flt)));
B(items,ls.length?ls.map(c=>{let un=c.unread&&c.id!==r;return e("a.chat-item",{href:"#/messages/"+c.id,class:(c.id===r?"on ":"")+(un?"unread":"")},MsgAvatar(c,46),e("div.ci-main",e("div.ci-top",e("span.ci-name",c.name),e("span.ci-time",MsgAgo(c.last&&c.last.createdAt))),e("div.ci-bot",e("span.ci-prev",c.last?(c.last.authorId===u.id?"Vous : ":"")+c.last.text:"Nouvelle conversation"),un?e("span.badge.accent",c.unread):null)))}):e("p.muted",{style:{padding:"18px 16px",margin:0}},flt?"Aucune conversation ne correspond.":"Aucune conversation. Démarrez-en une avec un ami."))}
async function drawThread(){W(thread);if(!r){C(thread,V({icon:"chat",title:"Vos conversations",text:"Échangez en privé ou en groupe : équipe de chasse, amis de pêche, ACCA…"}));return null}
let f;try{f=await v.get("/conversations/"+r+"/messages")}catch(er){C(thread,V({icon:"alert",title:"Conversation introuvable",text:er.message,action:x("Retour",{href:"#/messages",kind:"primary"})}));return null}
try{nt("conv:join",r)}catch{}
let g=f.conversation,msgs=e("div.chat-msgs",{role:"log","aria-live":"polite","aria-label":"Messages"}),typing=e("div.chat-typing"),prev=null,day=null;
let near=()=>msgs.scrollHeight-msgs.scrollTop-msgs.clientHeight<140,bottom=()=>{msgs.scrollTop=msgs.scrollHeight};
function add(m){let d=new Date(m.createdAt).toDateString(),dc=d!==day;if(dc){day=d;C(msgs,e("div.chat-day",M.isToday(m.createdAt)?"Aujourd’hui":M.day(m.createdAt)))}
let mine=m.authorId===u.id,first=!prev||prev.authorId!==m.authorId||dc||new Date(m.createdAt)-new Date(prev.createdAt)>3e5,grp=g.type==="group"&&!mine;prev=m;
C(msgs,e("div.msg-row",{class:(mine?"mine ":"")+(first?"first":"")},grp?(first?oe(m.author||{name:"?"},28):e("span.msg-gap")):null,e("div.bubble",{class:mine?"mine":""},grp&&first?e("div.who",(m.author&&m.author.name)||"Membre"):null,m.share&&m.share.kind==="listing"?e("a.msg-share",{href:"#/bourse"},b("swap"),e("span","Annonce : "+m.share.title)):null,m.text?e("div.txt",MsgLink(m.text)):null,e("div.meta",M.time(m.createdAt)))))}
f.messages.length?f.messages.forEach(add):C(msgs,e("div.chat-empty",e("b","Nouvelle conversation"),e("span","Écrivez le premier message.")));
let ta=e("textarea.input",{rows:1,placeholder:"Votre message…","aria-label":"Votre message",maxlength:2000}),send=x("",{icon:"send",kind:"primary",title:"Envoyer",onClick:()=>go()});send.setAttribute("aria-label","Envoyer");send.disabled=!0;
let grow=()=>{ta.style.height="auto";ta.style.height=Math.min(ta.scrollHeight,132)+"px";send.disabled=!ta.value.trim()};
ta.addEventListener("input",()=>{grow();if(Date.now()-lastTy>2e3){lastTy=Date.now();try{nt("typing",{conversationId:r})}catch{}}});
ta.addEventListener("focus",()=>{document.documentElement.classList.add("chat-focus");setTimeout(bottom,250);setTimeout(bottom,600)});ta.addEventListener("blur",()=>setTimeout(()=>{document.activeElement!==ta&&document.documentElement.classList.remove("chat-focus")},150));
ta.addEventListener("keydown",ev=>{if(ev.key==="Enter"&&!ev.shiftKey&&!ev.isComposing){ev.preventDefault();go()}});
async function go(){let tx=ta.value.trim();if(!tx)return;ta.value="";grow();try{await v.post("/conversations/"+r+"/messages",{text:tx})}catch(er){A(er.message,"err");ta.value=tx;grow()}ta.focus()}
let sub=g.type==="group"?(g.members||[]).length+" membres · "+(g.members||[]).map(y=>y.name.split(" ")[0]).join(", "):(g.others[0]&&g.others[0].city)||"";
C(thread,e("div.chat-head",e("a.icon-btn.mobile-back",{href:"#/messages","aria-label":"Retour aux conversations"},b("back")),MsgAvatar(g,40),e("div.chat-head-t",e("b",g.name),e("div.tiny.muted",sub)),g.type==="direct"&&g.others[0]?x("Profil",{kind:"ghost",size:"sm",href:"#/profil/"+g.others[0].id}):null),msgs,typing,e("div.chat-compose",ta,send));
requestAnimationFrame(bottom);
let D=convs.find(y=>y.id===r);if(D&&D.unread){w.unread.messages=Math.max(0,w.unread.messages-D.unread);D.unread=0;j.emit("unread");drawList()}
return{onMessage(y){if(y.conversationId!==r)return;let nb=near()||y.authorId===u.id;let em=msgs.querySelector(".chat-empty");em&&em.remove();add(y);typing.textContent="";nb&&bottom();v.post("/conversations/"+r+"/read").catch(()=>{})},onTyping(y){if(y.conversationId!==r)return;typing.textContent=y.user.name.split(" ")[0]+" écrit…";clearTimeout(typT);typT=setTimeout(()=>{typing.textContent=""},3e3)}}}
drawList();C(t,q({title:"Messagerie",subtitle:"Conversations privées et groupes : équipe de chasse, sorties pêche, ACCA."},k({flush:!0},root)));
api=await drawThread();let kbOff=MsgKb(root);
let offs=[j.on("rt:message:new",async y=>{api&&api.onMessage(y);convs=await v.get("/conversations");drawList()}),j.on("rt:message:badge",async()=>{convs=await v.get("/conversations");drawList()}),j.on("rt:conversation:new",async()=>{convs=await v.get("/conversations");drawList()}),j.on("rt:typing",y=>api&&api.onTyping(y))];
return()=>{offs.forEach(f=>f()),clearTimeout(typT),kbOff()}}
var MsgM={};le(MsgM,{default:()=>MsgView});var MsgI=H(()=>{});
