/* ===== 2.0 : Questions & réponses, groupes locaux ===== */
async function QaView(t){let u=w.user,tab=Pe.get("qa:tab","q"),act="tous",openId=null,root=e("div.stack"),head=e("div"),stopFn=()=>{};
const DEPTS={"41":"Loir-et-Cher","45":"Loiret","37":"Indre-et-Loire","18":"Cher","36":"Indre","28":"Eure-et-Loir","72":"Sarthe","49":"Maine-et-Loire","85":"Vendée","33":"Gironde","40":"Landes"};
const dn=d=>d?(DEPTS[d]?d+" · "+DEPTS[d]:"Département "+d):"";
const seg=()=>e("div.seg",{role:"tablist"},[["q","Questions"],["g","Groupes locaux"]].map(([k1,l])=>e("button",{type:"button",role:"tab","aria-selected":tab===k1,class:tab===k1?"on":"",onclick:()=>{tab=k1;openId=null;Pe.set("qa:tab",k1);draw()}},l)));
const actSeg=()=>e("div.seg",[["tous","Tout"],["chasse","Chasse"],["peche","Pêche"]].map(([k1,l])=>e("button",{type:"button",class:act===k1?"on":"",onclick:()=>{act=k1;draw()}},l)));
async function ask(){let ok=await Q({title:"Poser une question",intro:"La communauté vous répond. Soyez précis : lieu, période, contexte.",fields:[{name:"title",label:"Votre question",required:!0,placeholder:"Ex. : Quelle cartouche pour le grand gibier en Sologne ?"},{name:"body",label:"Détails",type:"textarea",placeholder:"Contexte, ce que vous avez déjà essayé…"},{name:"activity",label:"Domaine",type:"select",required:!0,value:w.season==="peche"?"peche":"chasse",options:[{value:"chasse",label:"Chasse"},{value:"peche",label:"Pêche"},{value:"nature",label:"Nature"}]}],submit:"Publier",onSubmit:d=>v.post("/questions",d)});ok&&(A("Question publiée.","ok"),draw())}
async function newGroup(){let ok=await Q({title:"Créer un groupe local",intro:"Un groupe réunit les passionnés d’un département : échanges, entraide, sorties.",fields:[{name:"name",label:"Nom du groupe",required:!0,placeholder:"Ex. : Pêcheurs de Loire 41"},{name:"department",label:"Département (n°)",required:!0,value:u.department||""},{name:"activity",label:"Domaine",type:"select",required:!0,value:w.season==="peche"?"peche":"chasse",options:[{value:"chasse",label:"Chasse"},{value:"peche",label:"Pêche"},{value:"nature",label:"Nature"}]},{name:"description",label:"Description",type:"textarea"}],submit:"Créer",onSubmit:d=>v.post("/groups",d)});ok&&(A("Groupe créé.","ok"),draw())}
async function list(){let qs=await v.get("/questions"+(act!=="tous"?"?activity="+act:""));return qs.length?e("div.stack",qs.map(z=>e("a.panel.qa-q",{href:"javascript:void 0",onclick:ev=>{ev.preventDefault();openId=z.id;draw()}},e("div.qa-card",e("div.pill-row",zn(z.activity),z.bestAnswerId?L("Résolu","ok","check"):L(z.answers+" réponse"+(z.answers>1?"s":""))),e("h3.display",{style:{margin:0,fontSize:"20px"}},z.title),z.body?e("div.small.muted",z.body.slice(0,140)+(z.body.length>140?"…":"")):null,e("div.row.small.muted",{style:{gap:"8px"}},oe(z.author,24),e("span",z.author.name),e("span","·"),Ce(z.createdAt)))))):V({icon:"chat",title:"Aucune question ici pour l’instant",text:"Soyez le premier à poser une question à la communauté.",action:x("Poser une question",{kind:"primary",icon:"plus",onClick:ask})})}
async function detail(){let z=await v.get("/questions/"+openId),mine=z.author.id===u.id,mod=["admin","moderator"].includes(u.role),ta=e("textarea.input",{placeholder:"Votre réponse…",style:{minHeight:"90px"},maxlength:1500});
return e("div.stack",e("div",x("← Toutes les questions",{kind:"ghost",size:"sm",onClick:()=>{openId=null;draw()}})),k({},e("div.pill-row",zn(z.activity),z.bestAnswerId?L("Résolu","ok","check"):null),e("h2.display",{style:{margin:"10px 0 6px",fontSize:"24px"}},z.title),z.body?e("p",{style:{whiteSpace:"pre-wrap",margin:"0 0 10px"}},z.body):null,e("div.row.small.muted",{style:{gap:"8px"}},oe(z.author,24),e("span",z.author.name),e("span","·"),Ce(z.createdAt)),mine||mod?e("div",{style:{marginTop:"12px"}},x("Supprimer",{icon:"trash",size:"sm",kind:"ghost",onClick:async()=>{if(await ve({title:"Supprimer la question ?",text:z.title,confirm:"Supprimer",danger:!0})){try{await v.del("/questions/"+z.id);openId=null;A("Question supprimée.");draw()}catch(er){A(er.message,"err")}}}})):null),k({title:z.list.length+" réponse"+(z.list.length>1?"s":"")},z.list.length?e("div.stack",z.list.map(a=>e("div.qa-answer"+(a.id===z.bestAnswerId?".best":""),e("div.row.small",{style:{gap:"8px",marginBottom:"6px"}},oe(a.author,24),e("b",a.author.name),e("span.muted",Ce(a.createdAt)),a.id===z.bestAnswerId?L("Meilleure réponse","ok","check"):null),e("div",{style:{whiteSpace:"pre-wrap"}},a.text),mine&&a.id!==z.bestAnswerId?e("div",{style:{marginTop:"8px"}},x("Choisir comme meilleure réponse",{size:"sm",icon:"check",onClick:async()=>{try{await v.post(`/questions/${z.id}/best`,{answerId:a.id});A("Merci, la question est marquée comme résolue.","ok");draw()}catch(er){A(er.message,"err")}}})):null))):e("p.muted",{style:{margin:0}},"Pas encore de réponse.")),k({title:"Répondre"},e("div.stack",{style:{gap:"10px"}},ta,x("Publier ma réponse",{kind:"primary",icon:"send",onClick:async()=>{if(ta.value.trim().length<3){A("Écrivez une réponse.","warn");return}try{await v.post(`/questions/${z.id}/answers`,{text:ta.value});A("Réponse publiée.","ok");draw()}catch(er){A(er.message,"err")}}}))))}
async function groups(){let gs=await v.get("/groups"),mineD=u.department;gs.sort((a,b2)=>(b2.joined-a.joined)||((b2.department===mineD)-(a.department===mineD))||a.name.localeCompare(b2.name));let fl=gs.filter(g=>act==="tous"||g.activity===act);return fl.length?e("div.grid.g-2",fl.map(g=>k({},e("div.row",{style:{alignItems:"flex-start"}},e("span.ic",{style:{width:"46px",height:"46px",borderRadius:"14px",display:"grid",placeItems:"center",background:"var(--accent-soft)",color:"var(--accent)",flex:"none"}},b("users")),e("div.grow",e("h3.display",{style:{margin:0,fontSize:"20px"}},g.name),e("div.small.muted",dn(g.department)+" · "+g.members+" membre"+(g.members>1?"s":""))),zn(g.activity)),g.description?e("p.small",{style:{margin:"10px 0 0"}},g.description):null,e("div.row.wrap",{style:{gap:"8px",marginTop:"12px"}},g.joined?L("Vous en faites partie","ok","check"):null,x(g.joined?"Quitter":"Rejoindre",{size:"sm",kind:g.joined?"ghost":"primary",icon:g.joined?null:"plus",onClick:async()=>{try{await v.post(`/groups/${g.id}/${g.joined?"leave":"join"}`,{});A(g.joined?"Vous avez quitté le groupe.":"Bienvenue dans le groupe !","ok");draw()}catch(er){A(er.message,"err")}}}))))):V({icon:"users",title:"Aucun groupe pour ce domaine",text:"Créez le premier groupe de votre département.",action:x("Créer un groupe",{kind:"primary",icon:"plus",onClick:newGroup})})}
async function draw(){let myT=++stamp;root.textContent="";let body;try{body=tab==="q"?(openId?await detail():await list()):await groups()}catch(er){body=V({icon:"alert",title:"Chargement impossible",text:er.message||"Réessayez dans un instant."})}if(myT!==stamp)return;head.textContent="";head.append(e("div.row.wrap",{style:{gap:"12px",justifyContent:"space-between"}},seg(),openId?null:actSeg(),openId?null:(tab==="q"?x("Poser une question",{icon:"plus",kind:"primary",onClick:ask}):x("Créer un groupe",{icon:"plus",kind:"primary",onClick:newGroup}))));root.append(body)}
let stamp=0;C(t,q({title:"Entraide & groupes",subtitle:"Posez vos questions à la communauté et retrouvez les passionnés de votre département."},e("div.stack",head,root)));await draw();return stopFn}
var QaM={};le(QaM,{default:()=>QaView});var QaI=H(()=>{});
var SorM={};le(SorM,{default:()=>SortieView});var SorI=H(()=>{});
var EauM={};le(EauM,{default:()=>WaterView});var EauI=H(()=>{});
var ShrM={};le(ShrM,{default:()=>ShareView});var ShrI=H(()=>{});
