/* ===== conducteurs de chien de sang : liste officielle UNUCR par département ===== */
const SG_DEPT={"01": "Ain", "02": "Aisne", "03": "Allier", "04": "Alpes-de-Haute-Provence", "05": "Hautes-Alpes", "06": "Alpes-Maritimes", "07": "Ardèche", "08": "Ardennes", "09": "Ariège", "10": "Aube", "11": "Aude", "12": "Aveyron", "13": "Bouches-du-Rhône", "14": "Calvados", "15": "Cantal", "16": "Charente", "17": "Charente-Maritime", "18": "Cher", "19": "Corrèze", "20": "Corse", "21": "Côte-d’Or", "22": "Côtes-d’Armor", "23": "Creuse", "24": "Dordogne", "25": "Doubs", "26": "Drôme", "27": "Eure", "28": "Eure-et-Loir", "29": "Finistère", "30": "Gard", "31": "Haute-Garonne", "32": "Gers", "33": "Gironde", "34": "Hérault", "35": "Ille-et-Vilaine", "36": "Indre", "37": "Indre-et-Loire", "38": "Isère", "39": "Jura", "40": "Landes", "41": "Loir-et-Cher", "42": "Loire", "43": "Haute-Loire", "44": "Loire-Atlantique", "45": "Loiret", "46": "Lot", "47": "Lot-et-Garonne", "48": "Lozère", "49": "Maine-et-Loire", "50": "Manche", "51": "Marne", "52": "Haute-Marne", "53": "Mayenne", "54": "Meurthe-et-Moselle", "55": "Meuse", "56": "Morbihan", "57": "Moselle", "58": "Nièvre", "59": "Nord", "60": "Oise", "61": "Orne", "62": "Pas-de-Calais", "63": "Puy-de-Dôme", "64": "Pyrénées-Atlantiques", "65": "Hautes-Pyrénées", "66": "Pyrénées-Orientales", "67": "Bas-Rhin", "68": "Haut-Rhin", "69": "Rhône", "70": "Haute-Saône", "71": "Saône-et-Loire", "72": "Sarthe", "73": "Savoie", "74": "Haute-Savoie", "75": "Paris", "76": "Seine-Maritime", "77": "Seine-et-Marne", "78": "Yvelines", "79": "Deux-Sèvres", "80": "Somme", "81": "Tarn", "82": "Tarn-et-Garonne", "83": "Var", "84": "Vaucluse", "85": "Vendée", "86": "Vienne", "87": "Haute-Vienne", "88": "Vosges", "89": "Yonne", "90": "Territoire de Belfort", "91": "Essonne", "92": "Hauts-de-Seine", "93": "Seine-Saint-Denis", "94": "Val-de-Marne", "95": "Val-d’Oise"};
function SgKey(){return "sang.contacts"}
function SgLoad(){return Pe.get(SgKey(),[])}
function SgSave(a){Pe.set(SgKey(),a)}
async function SgView(t){let dep="",qtxt="",data=SG_DATA,res=e("div.stack"),mine=e("div.stack");
const tel=s=>(s||"").replace(/[^\d+]/g,""),fr=s=>{let p=(s||"").split("/");return p.length===3?p[0]+"/"+p[1]+"/"+p[2]:s||""},iso=s=>{let d=new Date(s);return isNaN(d)?s:d.toLocaleDateString("fr-FR")};
try{let r=await fetch("sang-data.json",{cache:"no-store"});if(r.ok){let j=await r.json();j&&j.d&&(j.fetched||"")>=(SG_DATA.fetched||"")&&(data=j)}}catch(_){}
const nb=d=>(data.d[d]||[]).length;
function phone(n){return e("a.btn.primary.sm",{href:"tel:"+tel(n),style:{whiteSpace:"nowrap"}},"Appeler "+n)}
function drawRes(){W(res);if(!dep){C(res,e("div.small.muted","Choisissez votre département pour voir les conducteurs agréés les plus proches."));return}
let all=data.d[dep]||[],f=qtxt.trim().toLowerCase(),list=f?all.filter(r=>(r[0]+" "+r[2]+" "+r[1]).toLowerCase().includes(f)):all;
C(res,e("div.small",e("b",`${dep} · ${SG_DEPT[dep]||""}`)," : ",all.length?`${all.length} conducteur${all.length>1?"s":""} agréé${all.length>1?"s":""} dans la liste officielle`:"aucun conducteur dans la liste officielle"));
if(!all.length){C(res,e("div.small.muted","Essayez un département voisin : un conducteur peut se déplacer. Vous pouvez aussi joindre la Fédération départementale des chasseurs ou le délégué départemental UNUCR."),e("a.btn.ghost.sm",{href:"https://www.unucr.fr/delegations-et-assocations-departementales",target:"_blank",rel:"noopener noreferrer"},"Délégués départementaux UNUCR ↗"));return}
if(all.length>8)C(res,e("div.field",e("input",{type:"search",placeholder:"Filtrer par commune ou nom…",value:qtxt,oninput:ev=>{qtxt=ev.target.value;drawList(all)}})));
res.appendChild(listBox);drawList(all)}
let listBox=e("div.stack");
function drawList(all){W(listBox);let f=qtxt.trim().toLowerCase(),list=f?all.filter(r=>(r[0]+" "+r[2]+" "+r[1]).toLowerCase().includes(f)):all;
if(!list.length){C(listBox,e("div.small.muted","Aucun résultat."));return}
list.forEach(r=>C(listBox,e("div.row",{style:{gap:"10px",alignItems:"center",flexWrap:"wrap",padding:"10px 0",borderTop:"1px solid var(--line,#0001)"}},
e("div.small",{style:{flex:"1 1 160px",minWidth:0}},e("b",r[0]),e("div.tiny.muted",r[2]+" ("+r[1]+")")),
e("div.row",{style:{gap:"8px",flexWrap:"wrap"}},r[3]?phone(r[3]):null,r[4]?phone(r[4]):null))))}
function drawMine(){W(mine);let a=SgLoad();
if(!a.length){C(mine,e("div.small.muted","Aucun contact enregistré. Ajoutez ici votre conducteur habituel ou celui de votre société de chasse. Ils restent sur cet appareil."));return}
a.forEach(c=>C(mine,e("div.row",{style:{gap:"10px",alignItems:"center",flexWrap:"wrap",padding:"10px 0",borderTop:"1px solid var(--line,#0001)"}},
e("div.small",{style:{flex:"1 1 160px",minWidth:0}},e("b",c.name),e("div.tiny.muted",[c.place,c.dept&&"("+c.dept+")",c.note].filter(Boolean).join(" · "))),
e("div.row",{style:{gap:"8px",flexWrap:"wrap"}},c.phone?phone(c.phone):null,
x("Supprimer",{size:"sm",kind:"ghost",icon:"trash",onClick:async()=>{await ve({title:"Supprimer ce contact ?",text:c.name,confirm:"Supprimer",danger:!0})&&(SgSave(SgLoad().filter(z=>z.id!==c.id)),drawMine())}})))))}
async function add(){await Q({title:"Ajouter un conducteur",intro:"Pour un conducteur qui n’est pas dans la liste officielle (par exemple celui de votre société de chasse).",submit:"Enregistrer",fields:[{name:"name",label:"Nom et prénom",required:!0},{name:"phone",label:"Téléphone",placeholder:"06 00 00 00 00",required:!0},{name:"place",label:"Commune"},{name:"dept",label:"Département",placeholder:"45"},{name:"note",label:"Remarque (facultatif)",placeholder:"Chien : teckel, brachet…"}],onSubmit:async i=>{let a=SgLoad();a.push({id:"s"+Date.now().toString(36),name:i.name.trim(),phone:i.phone.trim(),place:(i.place||"").trim(),dept:(i.dept||"").trim(),note:(i.note||"").trim()});SgSave(a);drawMine();A("Contact ajouté.")}})}
let opts=Object.keys(SG_DEPT).sort().map(c=>e("option",{value:c},`${c} · ${SG_DEPT[c]} (${nb(c)})`));
let sel=e("select",{onchange:ev=>{dep=ev.target.value;qtxt="";drawRes()}},e("option",{value:""},"— Mon département —"),...opts);
let near=x("Me localiser",{icon:"pin",size:"sm",kind:"ghost",onClick:async()=>{try{let p=await Ee(),r=await fetch(`https://geo.api.gouv.fr/communes?lat=${p.lat??p.latitude}&lon=${p.lng??p.lon??p.longitude}&fields=codeDepartement&limit=1`),j=await r.json(),c=j&&j[0]&&j[0].codeDepartement;if(c&&SG_DEPT[c]){dep=c;sel.value=c;qtxt="";drawRes()}else A("Département introuvable.","err")}catch(_){A("Localisation indisponible : choisissez votre département dans la liste.","err")}}});
C(t,q({title:"Conducteurs de chien de sang",subtitle:"Retrouver un grand gibier blessé : que faire, et qui appeler dans votre département."},e("div.stack",
k({},e("div.row",{style:{gap:"10px",alignItems:"flex-start"}},b("info"),e("div",e("h3",{style:{margin:"0 0 6px"}},"Après un tir sur un grand gibier blessé"),
e("ol.small",{style:{margin:0,paddingLeft:"18px",lineHeight:"1.6"}},e("li","Ne piétinez pas le lieu du tir et n’y lancez pas de chien non spécialisé."),e("li","Repérez le poste, la direction de fuite, et balisez les indices (sang, poils, os) sans les ramasser."),e("li","Ne poursuivez pas l’animal : laissez-le se coucher, le temps compte."),e("li","Appelez rapidement un conducteur agréé de votre secteur, puis prévenez le responsable de la chasse.")))),
e("div.small.muted",{style:{marginTop:"10px"}},"Le conducteur agréé UNUCR (Union Nationale pour l’Utilisation de Chiens de Rouge) intervient avec un chien de rouge ; un défraiement est d’usage, à voir avec lui.")),
k({title:"Conducteurs agréés par département",sub:`${data.count} conducteurs · liste officielle UNUCR du ${fr(data.listDate)}`},
e("div.field",e("label","Département"),e("div.row",{style:{gap:"8px",flexWrap:"wrap",alignItems:"center"}},e("div",{style:{flex:"1 1 220px",minWidth:0}},sel),near)),res,
e("div.tiny.muted",{style:{marginTop:"12px"}},`Source : liste officielle des conducteurs agréés de l’UNUCR (${data.listDate}), reprise le ${iso(data.fetched)} et revérifiée chaque mois. Une personne retirée de la liste officielle disparaît ici à la mise à jour suivante. `,e("a",{href:data.sourceUrl,target:"_blank",rel:"noopener noreferrer"},"Voir la liste officielle ↗"))),
k({title:"Mes contacts",action:x("Ajouter",{icon:"plus",kind:"primary",size:"sm",onClick:add})},mine),
e("div.panel.tint",e("div.row",b("info"),e("div.small","Ces conducteurs sont des bénévoles : un numéro de la liste peut être occupé ou injoignable, appelez-en plusieurs si besoin. Une personne qui souhaite être retirée ou corrigée doit en faire la demande à l’UNUCR. Le 112 reste le numéro d’urgence en cas d’accident corporel."))))));
drawRes();drawMine()}
var SgM={};le(SgM,{default:()=>SgView});var SgI=H(()=>{});
