/* ===== tableaux d'espèces : chassables en France / poissons d'eau douce ===== */
const SP_SRC={chasse:"https://aida.ineris.fr/node/32738/printable/pdf",peche:"https://aida.ineris.fr/node/33227/printable/pdf"};
// [nom, catégorie, particularités, fiable(1=source officielle lue / 0=à vérifier)]
const SP_CHASSE=[
["Cerf élaphe","Grand gibier (mammifère)","Plan de chasse légal : bracelet obligatoire",1],["Cerf sika","Grand gibier (mammifère)","Plan de chasse légal : bracelet obligatoire",1],["Chevreuil","Grand gibier (mammifère)","Plan de chasse légal : bracelet obligatoire",1],["Daim","Grand gibier (mammifère)","Plan de chasse légal : bracelet obligatoire",1],["Chamois isard","Grand gibier (mammifère)","Plan de chasse légal : bracelet obligatoire",1],["Mouflon méditerranéen","Grand gibier (mammifère)","Plan de chasse légal : bracelet obligatoire",1],["Sanglier","Grand gibier (mammifère)","Dates, plan de gestion et modalités fixés par chaque département",1],
["Lièvre brun","Petit gibier (mammifère)","Prélèvement encadré localement (arrêté préfectoral)",0],["Lièvre variable","Petit gibier (mammifère)","Montagne : encadré localement",0],["Lapin de garenne","Petit gibier (mammifère)","",0],["Marmotte","Petit gibier (mammifère)","Montagne : encadré localement",0],["Blaireau","Petit gibier (mammifère)","Périodes spécifiques fixées par arrêté (vénerie sous terre)",0],
["Renard","Mammifère prédateur","Peut être classé ESOD selon le département",1],["Fouine","Mammifère prédateur","Peut être classé ESOD selon le département",1],["Martre","Mammifère prédateur","Peut être classé ESOD selon le département",1],["Belette","Mammifère prédateur","Peut être classé ESOD selon le département",1],["Hermine","Mammifère prédateur","",0],["Putois","Mammifère prédateur","",0],
["Faisan de chasse","Oiseau sédentaire","",0],["Perdrix rouge","Oiseau sédentaire","",0],["Perdrix grise","Oiseau sédentaire","",0],["Perdrix bartavelle","Oiseau sédentaire","Montagne : encadré localement",0],["Colin","Oiseau sédentaire","",0],["Gélinotte des bois","Oiseau sédentaire","Montagne : encadré localement",0],["Lagopède alpin","Oiseau sédentaire","Moratoire proposé en 2025 : voir l’arrêté de la saison",0],["Tétras lyre","Oiseau sédentaire","Coq maillé seulement ; interdit dans certains départements",1],["Tétras urogalle (grand tétras)","Oiseau sédentaire","Coq maillé seulement ; protégé dans plusieurs régions",1],
["Corneille noire","Oiseau sédentaire","Peut être classée ESOD selon le département",1],["Corbeau freux","Oiseau sédentaire","Peut être classé ESOD selon le département",1],["Pie bavarde","Oiseau sédentaire","Peut être classée ESOD selon le département",1],["Geai des chênes","Oiseau sédentaire","Peut être classé ESOD selon le département",1],["Étourneau sansonnet","Oiseau sédentaire","Peut être classé ESOD selon le département",1],
["Bécasse des bois","Oiseau de passage","Prélèvement maximal : 30 par chasseur et par saison ; carnet obligatoire",1],["Caille des blés","Oiseau de passage","Déclaration en temps réel (ChassAdapt) ; limitation proposée en 2025",1],["Tourterelle des bois","Oiseau de passage","Déclaration en temps réel (ChassAdapt) ; espèce vulnérable (UICN)",1],["Tourterelle turque","Oiseau de passage","",0],["Pigeon ramier","Oiseau de passage","",0],["Pigeon colombin","Oiseau de passage","",0],["Pigeon biset","Oiseau de passage","",0],["Alouette des champs","Oiseau de passage","Fermeture plus précoce possible (ex. 31 janvier)",1],["Merle noir","Oiseau de passage","",0],["Grive musicienne","Oiseau de passage","",0],["Grive draine","Oiseau de passage","",0],["Grive litorne","Oiseau de passage","",0],["Grive mauvis","Oiseau de passage","Limitation proposée en 2025 : voir l’arrêté de la saison",0],
["Canard colvert","Gibier d’eau","Grenaille sans plomb en zone humide",1],["Canard chipeau","Gibier d’eau","Grenaille sans plomb en zone humide",1],["Canard pilet","Gibier d’eau","Limitation proposée en 2025 : voir l’arrêté de la saison",0],["Canard siffleur","Gibier d’eau","Limitation proposée en 2025 : voir l’arrêté de la saison",0],["Canard souchet","Gibier d’eau","Limitation proposée en 2025 : voir l’arrêté de la saison",0],["Sarcelle d’hiver","Gibier d’eau","Limitation proposée en 2025 : voir l’arrêté de la saison",0],["Sarcelle d’été","Gibier d’eau","",0],["Fuligule milouin","Gibier d’eau","Déclaration en temps réel (ChassAdapt) ; moratoire proposé en 2025",1],["Fuligule milouinan","Gibier d’eau","",0],["Fuligule morillon","Gibier d’eau","",0],["Nette rousse","Gibier d’eau","",0],["Garrot à l’œil d’or","Gibier d’eau","",0],["Eider à duvet","Gibier d’eau","",0],["Harelde de Miquelon","Gibier d’eau","",0],["Macreuse brune","Gibier d’eau","",0],["Macreuse noire","Gibier d’eau","",0],["Oie cendrée","Gibier d’eau","",0],["Oie des moissons","Gibier d’eau","",0],["Oie rieuse","Gibier d’eau","",0],["Foulque macroule","Gibier d’eau","",0],["Poule d’eau","Gibier d’eau","",0],["Râle d’eau","Gibier d’eau","",0],["Bécassine des marais","Gibier d’eau","Fermeture plus précoce possible (ex. 31 janvier)",1],["Bécassine sourde","Gibier d’eau","Fermeture plus précoce possible (ex. 31 janvier)",1],["Vanneau huppé","Gibier d’eau et oiseau de passage","Fermeture plus précoce possible (ex. 31 janvier)",1],["Pluvier doré","Gibier d’eau","Fermeture plus précoce possible (ex. 31 janvier)",1],["Pluvier argenté","Gibier d’eau","",0],["Huîtrier pie","Gibier d’eau","",0],["Bécasseau maubèche","Gibier d’eau","",0],["Chevalier aboyeur","Gibier d’eau","",0],["Chevalier arlequin","Gibier d’eau","",0],["Chevalier combattant","Gibier d’eau","",0],["Chevalier gambette","Gibier d’eau","",0],["Courlis corlieu","Gibier d’eau","",0],["Courlis cendré","Gibier d’eau","Moratoire : chasse interdite",1],["Barge à queue noire","Gibier d’eau","Moratoire : chasse interdite",1],["Barge rousse","Gibier d’eau","",0]];
const SP_PECHE=[
["Brochet","2e catégorie","50 cm (souvent 60 cm en local)","Fermeture du dernier dimanche de janvier au dernier samedi d’avril ; remise à l’eau obligatoire du 2e samedi de mars au dernier vendredi d’avril",1],["Sandre","2e catégorie","40 cm (souvent 50 cm en local)","Fermeture locale possible par arrêté",1],["Black-bass","2e catégorie","30 cm (souvent 40 cm en local)","Fermeture locale possible par arrêté",1],["Perche","2e catégorie","Pas de minimum national","",0],
["Truite fario","1re et 2e catégories","23 cm","Ouverture du 2e samedi de mars au 3e dimanche de septembre",1],["Truite arc-en-ciel","1re et 2e catégories","23 cm","Salmonidés : jusqu’à 10 par jour hors saumon et truite de mer",0],["Omble de fontaine","1re catégorie","23 cm","Salmonidés : jusqu’à 10 par jour hors saumon et truite de mer",1],["Omble chevalier","Lacs","23 cm","",1],["Ombre commun","1re catégorie","30 cm","Ouverture le 3e samedi de mai ; date de clôture à vérifier localement",1],["Corégone (féra, lavaret)","Lacs","30 cm","",1],["Cristivomer","Lacs","35 cm","",1],["Huchon","Rivières","70 cm","",1],
["Saumon atlantique","Migrateur","50 cm","Pêche fermée au niveau national en 2025 et 2026",1],["Truite de mer","Migrateur","35 cm","Autorisée en 2026 dans 5 départements seulement, avec autorisation",1],["Alose","Migrateur","30 cm","",1],["Lamproie marine","Migrateur","40 cm","Pêche interdite par de nombreux arrêtés locaux",1],["Lamproie fluviatile","Migrateur","20 cm","Pêche interdite par de nombreux arrêtés locaux",1],["Mulet","Estuaires","20 cm","",1],
["Anguille jaune","Migrateur","Pas de minimum national","Carnet de pêche obligatoire ; déclaration des captures sous 24 h depuis le 14 juin 2026 ; période fixée par arrêté ministériel",1],["Anguille argentée et civelle","Migrateur","—","Pêche interdite aux pêcheurs de loisir",1],
["Carpe commune","2e catégorie","Pas de minimum national","Pêche de nuit seulement sur parcours autorisés par arrêté préfectoral",1],["Gardon, brème, tanche","2e catégorie","Pas de minimum national","",0],["Chevesne, barbeau, hotu","Rivières","Pas de minimum national","",0],["Silure","2e catégorie","Pas de minimum national","Règles de remise à l’eau à vérifier auprès de l’AAPPMA",0],
["Poisson-chat, perche-soleil, pseudorasbora, goujon de l’Amour","Espèces exotiques envahissantes","—","Remise à l’eau interdite",1],["Écrevisses américaines et de Californie","Espèces exotiques envahissantes","—","Remise à l’eau interdite",1],["Écrevisses à pattes blanches, rouges, des torrents, à pattes grêles","Espèces autochtones","9 cm","Pêche interdite par beaucoup d’arrêtés locaux",0],["Grenouilles vertes et rousses","Amphibiens","8 cm","Périodes de pêche fixées localement",0],
["Esturgeon européen, apron du Rhône","Espèces protégées","—","Espèces protégées : capture interdite",0]];
const SP_FRAYERES="Arrêté du 8 décembre 1988 : les frayères et zones de reproduction de ces taxons sont protégées (ce n’est pas une interdiction de pêche) : lamproies (de Planer, marine, fluviatile), corégones, saumon atlantique, truites, omble chevalier, grande alose, alose feinte, ombre commun, brochet, barbeau méridional, vandoise, ide mélanote, bouvière, loche d’étang, loche de rivière, blennie fluviatile, apron.";
function SpTable(n){let rows=n==="chasse"?SP_CHASSE:SP_PECHE,qt="",cat="",wrap=e("div.stack",{style:{paddingBottom:"12px"}}),tb=e("div"),
norm=s=>(s||"").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,""),
cats=[...new Set(rows.map(r=>r[1]))];
function draw(){W(tb);let l=rows.filter(r=>(!cat||r[1]===cat)&&(!qt||norm(r[0]).includes(norm(qt))));
C(tb,l.length?e("div",...l.map(r=>{let ch=n==="chasse",ok=ch?r[3]:r[4],note=ch?r[2]:r[3];return e("div",{style:{padding:"11px 0",borderTop:"1px solid var(--line,#0001)"}},
e("div.row",{style:{justifyContent:"space-between",gap:"8px",alignItems:"flex-start",flexWrap:"wrap"}},e("div",{style:{flex:"1 1 180px",minWidth:0}},e("b",r[0]),e("div.tiny.muted",r[1]+(ch?"":" · taille min. : "+r[2]))),ok?L("Source officielle","accent","check"):L("À vérifier","gold")),
note?e("div.small",{style:{marginTop:"4px",lineHeight:"1.5"}},note):null)})):e("div.small.muted","Aucune espèce ne correspond."))}
let rowsN=n==="peche"?SP_PECHE:SP_CHASSE;
if(n==="peche"){rows=SP_PECHE.map(r=>[r[0],r[1],r[2],r[3],r[4]])}
C(wrap,e("div.row",{style:{gap:"8px",flexWrap:"wrap"}},e("div.field",{style:{flex:"1 1 200px",margin:0}},e("input",{type:"search",placeholder:"Rechercher une espèce…",oninput:ev=>{qt=ev.target.value;draw()}})),e("div.field",{style:{flex:"1 1 200px",margin:0}},e("select",{onchange:ev=>{cat=ev.target.value;draw()}},e("option",{value:""},"Toutes les catégories"),...cats.map(c=>e("option",{value:c},c))))),tb,
e("div.tiny.muted",n==="chasse"?["Liste des espèces de gibier dont la chasse est autorisée : arrêté du 26 juin 1987 modifié (", e("a",{href:SP_SRC.chasse,target:"_blank",rel:"noopener noreferrer"},"texte consolidé ↗"),"), soit ",String(rows.length)," lignes. Les moratoires et limitations changent d’une saison à l’autre : l’arrêté ministériel et l’arrêté préfectoral en vigueur font foi. Les espèces non listées sont protégées."]:["Tailles minimales nationales (art. R436-18 et arrêtés) ; les arrêtés préfectoraux peuvent les relever. ",SP_FRAYERES+" ",e("a",{href:SP_SRC.peche,target:"_blank",rel:"noopener noreferrer"},"Texte de 1988 ↗")]));
draw();return wrap}
