/* ===== 2.0 serveur : questions & groupes ===== */
function QaSeed(){if(window.__qaS)return;window.__qaS=1;if(se.questions.count()||se.groups.count())return;let us=se.users.all(),U=i=>(us[i%Math.max(us.length,1)]||{}).id,ago=h=>new Date(Date.now()-h*36e5).toISOString(),A1=(i,tx,h)=>({id:"a_"+Math.random().toString(36).slice(2,8),authorId:U(i),text:tx,createdAt:ago(h)});
let q1=se.questions.insert({authorId:U(2),title:"Quelle tenue pour les premières battues de la saison en Sologne ?",body:"Je débute à l’ACCA. Les matinées sont fraîches mais on marche beaucoup. Que conseillez-vous ?",activity:"chasse",department:"41",answers:[A1(0,"Plusieurs couches fines plutôt qu’une grosse veste, et du orange bien visible. Prévoyez des chaussures étanches : les sous-bois sont humides.",30),A1(1,"Gants fins pour garder le toucher de la détente, et une veste de rechange dans le véhicule.",26)],bestAnswerId:null,createdAt:ago(34)}),
q2=se.questions.insert({authorId:U(1),title:"Où trouver l’état de la réglementation pêche pour un étang privé ?",body:"Je ne sais pas si la carte de pêche suffit sur un étang communal.",activity:"peche",department:"41",answers:[A1(3,"Renseignez-vous auprès de la fédération départementale et de la mairie : les règles varient selon le plan d’eau.",12)],bestAnswerId:null,createdAt:ago(14)}),
q3=se.questions.insert({authorId:U(0),title:"Conseils pour tester son chien avant l’ouverture ?",body:"",activity:"chasse",department:"41",answers:[],bestAnswerId:null,createdAt:ago(3)});
[["Chasseurs du Loir-et-Cher","41","chasse","Entraide, covoiturage et infos terrain entre chasseurs du 41."],["Pêcheurs de Loire & Cher","41","peche","Spots, niveaux d’eau et bons plans entre pêcheurs."],["Chasseurs du Loiret","45","chasse","Les passionnés du 45, de la Sologne au Gâtinais."],["Nature & sentiers de Touraine","37","nature","Balades, observation et respect des usages partagés."],["Pêcheurs du Cher","18","peche","Rivières, étangs et carnets de prises."]].forEach(([n,d,a,ds],i)=>se.groups.insert({name:n,department:d,activity:a,description:ds,members:i<2?us.filter(u=>u.department==="41").slice(0,5+i).map(u=>u.id):[],createdBy:U(0)}))}
function QaAuthor(id){let u=se.users.get(id);return u?_t(u):{id:id,name:"Ancien membre"}}
function QaOut(z,full){let o={id:z.id,title:z.title,body:z.body,activity:z.activity,department:z.department,author:QaAuthor(z.authorId),createdAt:z.createdAt,bestAnswerId:z.bestAnswerId||null,answers:(z.answers||[]).length};if(full)o.list=(z.answers||[]).slice().sort((a,b2)=>(a.id===z.bestAnswerId?-1:b2.id===z.bestAnswerId?1:0)||a.createdAt.localeCompare(b2.createdAt)).map(a=>({...a,author:QaAuthor(a.authorId)}));return o}
Be.get("/questions",bt(async(t,r)=>{QaSeed();let n=t.query.activity;r.json(se.questions.all(z=>!n||n==="tous"||z.activity===n).sort((a,b2)=>b2.createdAt.localeCompare(a.createdAt)).map(z=>QaOut(z,!1)))}));
Be.get("/questions/:id",bt(async(t,r)=>{QaSeed();let z=se.questions.get(t.params.id);if(!z)throw new lt(404,"Question introuvable.");r.json(QaOut(z,!0))}));
Be.post("/questions",bt(async(t,r)=>{QaSeed();yr(t.body,{title:"string",activity:"string"});let ti=String(t.body.title).trim();if(ti.length<10)throw new lt(400,"La question est trop courte (10 caractères minimum).");let ac=["chasse","peche","nature"].includes(t.body.activity)?t.body.activity:"chasse";r.json(QaOut(se.questions.insert({authorId:t.user.id,title:ti.slice(0,140),body:String(t.body.body||"").trim().slice(0,1500),activity:ac,department:t.user.department||"",answers:[],bestAnswerId:null}),!0))}));
Be.post("/questions/:id/answers",bt(async(t,r)=>{let z=se.questions.get(t.params.id);if(!z)throw new lt(404,"Question introuvable.");let tx=String(t.body&&t.body.text||"").trim();if(tx.length<3)throw new lt(400,"Réponse trop courte.");if((z.answers||[]).length>=100)throw new lt(400,"Cette question a déjà beaucoup de réponses.");let a={id:"a_"+Math.random().toString(36).slice(2,8),authorId:t.user.id,text:tx.slice(0,1500),createdAt:new Date().toISOString()};r.json(QaOut(se.questions.update(z.id,{answers:[...(z.answers||[]),a]}),!0))}));
Be.post("/questions/:id/best",bt(async(t,r)=>{let z=se.questions.get(t.params.id);if(!z)throw new lt(404,"Question introuvable.");if(z.authorId!==t.user.id)throw new lt(403,"Seul l’auteur de la question peut choisir la meilleure réponse.");if(!(z.answers||[]).some(a=>a.id===t.body.answerId))throw new lt(400,"Réponse inconnue.");r.json(QaOut(se.questions.update(z.id,{bestAnswerId:t.body.answerId}),!0))}));
Be.delete("/questions/:id",bt(async(t,r)=>{let z=se.questions.get(t.params.id);if(!z)throw new lt(404,"Question introuvable.");if(z.authorId!==t.user.id&&!["admin","moderator"].includes(t.user.role))throw new lt(403,"Suppression non autorisée.");se.questions.remove(z.id);r.json({ok:!0})}));
function GrOut(g,u){return{id:g.id,name:g.name,department:g.department,activity:g.activity,description:g.description,members:(g.members||[]).length,joined:!!u&&(g.members||[]).includes(u.id)}}
Be.get("/groups",bt(async(t,r)=>{QaSeed();r.json(se.groups.all().map(g=>GrOut(g,t.user)))}));
Be.post("/groups",bt(async(t,r)=>{QaSeed();yr(t.body,{name:"string",department:"string"});let n=String(t.body.name).trim(),d=String(t.body.department).trim();if(n.length<4)throw new lt(400,"Le nom est trop court (4 caractères minimum).");if(!/^(\d{2,3}|2[AB])$/i.test(d))throw new lt(400,"Indiquez un numéro de département valide (ex. 41).");if(se.groups.all(g=>g.createdBy===t.user.id).length>=3)throw new lt(400,"Vous avez déjà créé 3 groupes.");let ac=["chasse","peche","nature"].includes(t.body.activity)?t.body.activity:"chasse";r.json(GrOut(se.groups.insert({name:n.slice(0,60),department:d.toUpperCase(),activity:ac,description:String(t.body.description||"").trim().slice(0,240),members:[t.user.id],createdBy:t.user.id}),t.user))}));
Be.post("/groups/:id/join",bt(async(t,r)=>{let g=se.groups.get(t.params.id);if(!g)throw new lt(404,"Groupe introuvable.");let m=g.members||[];r.json(GrOut(m.includes(t.user.id)?g:se.groups.update(g.id,{members:[...m,t.user.id]}),t.user))}));
Be.post("/groups/:id/leave",bt(async(t,r)=>{let g=se.groups.get(t.params.id);if(!g)throw new lt(404,"Groupe introuvable.");r.json(GrOut(se.groups.update(g.id,{members:(g.members||[]).filter(i=>i!==t.user.id)}),t.user))}));
