/* ===== 2.0 : Sortie en cours, alertes de proximité, niveaux d'eau ===== */
function HavM(a,b2){let R=6371008.8,k=Math.PI/180,dl=(b2.lat-a.lat)*k,dn=(b2.lng-a.lng)*k,x1=Math.sin(dl/2)**2+Math.cos(a.lat*k)*Math.cos(b2.lat*k)*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(x1))}
function TripEv(t,type,label){t.events=t.events||[];t.events.push({t:new Date().toISOString(),type:type,label:label})}
function TripSample(){let tr=TripGet();if(!tr||tr.status!=="active")return;let p=w.position;if(!p||p.approx||!isFinite(p.lat)||!isFinite(p.lng))return;try{LivePush(tr,p)}catch{}tr.track=tr.track||[];let l=tr.track[tr.track.length-1];if(p.accuracy>60)return;if(!l||HavM({lat:l[0],lng:l[1]},p)>Math.max(6,Math.min(15,(p.accuracy||0)*.6))){tr.track.push([+(+p.lat).toFixed(5),+(+p.lng).toFixed(5),Date.now()]);if(tr.track.length>3000)tr.track=tr.track.filter((q,i)=>i%2===0||i===tr.track.length-1);Pe.set(TripKey(),tr)}}
function TripKey(){return"trip:"+(w.user&&w.user.id)}
function TripGet(){return Pe.get(TripKey(),null)}
function TripSet(t){Pe.set(TripKey(),t);try{j.emit("trip",t)}catch{}try{FrSync(t)}catch{}try{LiveSync(t)}catch{}}
function TripFmt(ms){let s=Math.abs(Math.round(ms/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),c=s%60,p=n=>String(n).padStart(2,"0");return p(h)+":"+p(m)+":"+p(c)}
function TripHm(iso){let d=new Date(iso);return String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")}
function TripLocal(d){let p=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())+"T"+p(d.getHours())+":"+p(d.getMinutes())}
function TripAct(a){return{chasse:"chasse",peche:"pêche",nature:"balade nature"}[a]||a}
function TripMsg(t){let pos=w.position&&!w.position.approx?` Dernière position connue : https://www.openstreetmap.org/?mlat=${w.position.lat.toFixed(5)}&mlon=${w.position.lng.toFixed(5)}#map=16/${w.position.lat.toFixed(5)}/${w.position.lng.toFixed(5)}.`:"";return`Bonjour ${t.contact&&t.contact.name?t.contact.name:""}, je pars en sortie (${TripAct(t.activity)}${t.kind?", "+t.kind.toLowerCase():""}${t.dog?", avec chien":""}) : ${t.place||"secteur habituel"}. Départ ${TripHm(t.start)}, retour prévu à ${TripHm(t.returnAt)}.${t.note?" "+t.note+".":""}${pos} Si je n'ai pas donné de nouvelles une heure après, merci d'essayer de m'appeler puis de contacter les secours (112).`.replace(/\s+/g," ")}
async function TripCopy(txt){try{await navigator.clipboard.writeText(txt);A("Message copié : collez-le dans votre messagerie.","ok");return}catch{}let ta=e("textarea.input",{readonly:!0,style:{minHeight:"120px"}},txt),m=Le({title:"Message pour votre contact",body:e("div.stack",e("p.small.muted",{style:{margin:0}},"Sélectionnez le texte puis copiez-le."),ta)});setTimeout(()=>{ta.focus();ta.select()},50)}
function TripPillEl(){let a=e("a.trip-pill",{href:"#/sortie/chasse",hidden:!0}),up=()=>{let t=TripGet();if(!t||t.status!=="active"){a.hidden=!0;return}let d=new Date(t.returnAt)-Date.now();a.hidden=!1;a.href="#/sortie/"+(t.activity==="peche"?"peche":"chasse");a.className="trip-pill"+(d<0?" late":"");a.textContent=d<0?"En retard de "+TripFmt(d).slice(0,5):"Sortie · retour dans "+TripFmt(d).slice(0,5);if(d<0&&!t.lateNotified){t.lateNotified=!0;TripEv(t,"late","Heure de retour dépassée");TripSet(t);A("Heure de retour dépassée : confirmez que vous êtes rentré ou prolongez la sortie.","warn")}};up();window._tripTimer||(window._tripTimer=setInterval(()=>{try{TripSample();TripWake();j.emit("trip",TripGet())}catch{}},15000));j.on("trip",up);window._tripPosHook||(window._tripPosHook=1,document.addEventListener("visibilitychange",()=>{if(!document.hidden)TripWake()}),j.on("position",()=>{try{TripSample()}catch{}}));return a}
function ProxBanner(al,d){try{let tr=TripGet();if(tr&&tr.status==="active"){TripEv(tr,"alert","Alerte à proximité : "+(al.category||"signalement")+" (~"+d+" m)");Pe.set(TripKey(),tr)}}catch{}let bn=e("div.prox-banner",{role:"alert"},b("alert"),e("div.grow",e("b","Alerte à environ "+(d<100?"moins de 100":d)+" m"),e("div.small",al.category||"Signalement")),x("Voir",{size:"sm",href:"#/securite/"+al.id}),e("button.icon-btn",{type:"button","aria-label":"Fermer",style:{background:"transparent",borderColor:"rgba(255,255,255,.5)",color:"#fff",boxShadow:"none"},onclick:()=>bn.remove()},b("check")));document.body.append(bn);setTimeout(()=>bn.remove(),25000)}
function ProxStart(){if(window._prox)return;window._prox=1;let seen=new Set,chk=async()=>{if(!w.user||document.hidden||!Pe.get("prox:"+w.user.id,!0))return;let p=w.position;if(!p||p.approx)return;try{let ls=await v.get(`/alerts?status=open&lat=${p.lat}&lng=${p.lng}&radius=600`);ls.filter(a=>a.userId!==w.user.id&&!seen.has(a.id)&&a.location).forEach(a=>{seen.add(a.id);ProxBanner(a,Math.round(HavM(p,a.location)))})}catch{}};setInterval(chk,45000);setTimeout(chk,5000);try{j.on("rt:alert:new",a=>{let p=w.position;if(!w.user||!a||!a.location||!p||p.approx||!Pe.get("prox:"+w.user.id,!0))return;let d=HavM(p,a.location);d<=600&&!seen.has(a.id)&&(seen.add(a.id),ProxBanner(a,Math.round(d)))})}catch{}}
async function SortieView(t,pa){let ACT=pa&&pa.act==="peche"?"peche":pa&&pa.act==="chasse"?"chasse":(w.season==="peche"?"peche":"chasse"),PE=ACT==="peche",u=w.user,terrs=[],spots=[],tick=null;try{terrs=(await v.get("/territories")).filter(q=>q.kind==="personal")}catch{}if(PE)try{let sp=await v.get("/spots");spots=(Array.isArray(sp)?sp:[]).filter(z=>z&&z.name)}catch{}let SRC=PE?spots:terrs;
let stop=()=>{tick&&clearInterval(tick);tick=null},render=()=>{stop();t.textContent="";let cur=TripGet();C(t,q({title:PE?"Sortie pêche":"Sortie chasse",subtitle:PE?"Prévenez un proche : quel plan d’eau, à quelle heure vous rentrez. L’appli vous le rappelle.":"Prévenez un proche : où vous chassez et à quelle heure vous rentrez. L’appli vous le rappelle."},cur&&cur.status==="active"?(cur.activity===ACT||cur.activity==="nature"?Active(cur):Other(cur)):Form()))},
Form=()=>{let saved=Pe.get("contact:"+u.id,{name:"",phone:""}),act=ACT,ret=new Date(Date.now()+3*36e5);ret.setMinutes(Math.ceil(ret.getMinutes()/5)*5,0,0);
let KINDS=PE?["Du bord","En bateau / float-tube","En waders","Autre"]:["Approche / affût","Battue","Chasse devant soi","Autre"],sel=e("select.input",{id:"tr-kind"},KINDS.map(a=>e("option",{value:a},a))),dog=e("input",{type:"checkbox",id:"tr-dog"}),terr=e("select.input",{id:"tr-ter"},e("option",{value:""},PE?"Autre plan d’eau":"Autre lieu"),SRC.map(q=>e("option",{value:q.id},q.name))),place=e("input.input",{id:"tr-place",type:"text",placeholder:PE?"Ex. : étang des Brosses, rive nord":"Ex. : Bois des Brosses, parking route de Vouzon",maxlength:80}),when=e("input.input",{id:"tr-when",type:"datetime-local"}),cn=e("input.input",{id:"tr-cname",type:"text",placeholder:"Prénom du proche",maxlength:40}),cp=e("input.input",{id:"tr-cphone",type:"tel",placeholder:"Numéro (facultatif mais utile)",maxlength:20}),note=e("textarea.input",{id:"tr-note",placeholder:"Véhicule, immatriculation, chien, direction prévue…",style:{minHeight:"72px"},maxlength:200}),err=e("div.small",{style:{color:"var(--brick)",fontWeight:"600"}});when.value=TripLocal(ret);cn.value=saved.name||"";cp.value=saved.phone||"";terr.addEventListener("change",()=>{let q=SRC.find(z=>z.id===terr.value);q&&!place.value&&(place.value=q.name)});
let add=h=>x("+ "+h+" h",{kind:"ghost",size:"sm",onClick:()=>{let d=new Date(Date.now()+h*36e5);d.setMinutes(Math.ceil(d.getMinutes()/5)*5,0,0);when.value=TripLocal(d)}});
return e("div.grid.g-main",e("div.stack",k({title:"Je pars",sub:"Quelques secondes"},e("div.form-grid",e("div.field",e("label",{for:"tr-kind"},"Type de sortie"),sel),e("div.field",e("label",{for:"tr-ter"},PE?"Mon spot":"Mon territoire"),terr),e("div.field.full",e("label",{for:"tr-place"},PE?"Plan d’eau ou cours d’eau":"Lieu ou secteur"),place),e("div.field.full",e("label.check",dog,e("span",PE?"Je pars avec un compagnon (chien, ami)":"Je pars avec mon chien"))),e("div.field.full",e("label",{for:"tr-when"},"Heure de retour prévue"),when,e("div.row.wrap",{style:{gap:"6px"}},add(2),add(4),add(8))),e("div.field",e("label",{for:"tr-cname"},"Mon proche"),cn),e("div.field",e("label",{for:"tr-cphone"},"Son numéro"),cp),e("div.field.full",e("label",{for:"tr-note"},"À savoir (facultatif)"),note)),err,x("Démarrer la sortie",{icon:"play",kind:"primary",size:"block",onClick:()=>{err.textContent="";let r=new Date(when.value);if(isNaN(r)||r.getTime()<Date.now()+5*6e4){err.textContent="Choisissez une heure de retour dans le futur (au moins 5 minutes).";return}if(cn.value.trim().length<2){err.textContent="Indiquez le prénom d’un proche à prévenir.";return}let tt=SRC.find(z=>z.id===terr.value);Pe.set("contact:"+u.id,{name:cn.value.trim(),phone:cp.value.trim()});let trip={id:"trip_"+Date.now().toString(36),status:"active",activity:ACT,kind:sel.value,dog:dog.checked,territoryId:tt?tt.id:null,place:place.value.trim()||(tt?tt.name:""),start:new Date().toISOString(),returnAt:r.toISOString(),contact:{name:cn.value.trim(),phone:cp.value.trim()},note:note.value.trim()};TripEv(trip,"start","Départ"+(trip.place?" · "+trip.place:"")+" · retour prévu à "+TripHm(trip.returnAt));TripSample();TripSet(trip);A("Sortie démarrée. Copiez le message pour votre proche.","ok");render();TripCopy(TripMsg(trip))}}))),e("div.stack",k({title:"Comment ça marche",cls:"tint"},e("div.rm-step",e("div.n","1"),e("div","Vous indiquez où vous allez et l’heure de retour.")),e("div.rm-step",e("div.n","2"),e("div","Vous envoyez le message prêt à copier à votre proche.")),e("div.rm-step",e("div.n","3"),e("div","À l’heure dite, l’appli vous demande de confirmer votre retour.")),e("p.tiny.muted",{style:{margin:"10px 0 0"}},"L’appli ne peut pas prévenir seule votre proche : c’est lui qui, avec votre message, saura quand s’inquiéter.")),Prox(),k({title:PE?"Avant de partir":"Avant de partir",cls:"tint"},e("div.list",PE?[["/niveaux-eau","drop","Niveaux d’eau près de moi"],["/reglementation/peche","law","Réglementation pêche"]].map(([h,i,l])=>e("a.list-row",{href:"#"+h},e("span.ic",b(i)),e("div.grow.t",l),b("chevron"))):[["/angle-30","target","Calculateur d’angle de 30°"],["/territoires","pin","Mes territoires"],["/reglementation/chasse","law","Réglementation chasse"]].map(([h,i,l])=>e("a.list-row",{href:"#"+h},e("span.ic",b(i)),e("div.grow.t",l),b("chevron"))))),Hist()))},
Hist=()=>{let h=Pe.get("trips-hist:"+u.id,[]).filter(z=>z.activity===ACT||z.activity==="nature");return h.length?k({title:"Dernières sorties",action:e("a.link-more",{href:"#/historique/"+ACT},"Tout l’historique",b("chevron"))},e("div.list",h.slice(0,4).map(x1=>e("a.list-row",{href:x1.id?"#/sortie-detail/"+x1.id:"#/historique/"+ACT},e("span.ic",b("clock")),e("div.grow",e("div.t",(x1.place||TripAct(x1.activity))),e("div.s",M.dateTime(x1.start)+" → "+TripHm(x1.endedAt)+(x1.publishedId?" · publiée":""))),b("chevron"))))):k({title:"Historique"},e("p.small.muted",{style:{margin:0}},"Vos sorties terminées apparaîtront ici, avec leur déroulé. Vous pourrez en publier une au fil si vous le souhaitez."))},
Prox=()=>{let on=Pe.get("prox:"+u.id,!0),p=w.position,ok=p&&!p.approx,cb=e("input",{type:"checkbox",id:"prox-on",checked:on,onchange:z=>{Pe.set("prox:"+u.id,z.target.checked);A(z.target.checked?"Alertes de proximité activées.":"Alertes de proximité désactivées.")}});return k({title:"Alertes de proximité"},e("label.check",cb,e("span","Me prévenir d’une alerte à moins de 600 m",e("div.hint.muted.small",ok?"Votre position est suivie pendant que l’appli est ouverte.":"Position précise indisponible ici : activez la localisation (version hébergée, en https) pour recevoir ces alertes."))))},
Other=cur=>k({title:"Une sortie est déjà en cours"},e("p",{style:{margin:"0 0 12px"}},"Vous avez une sortie "+TripAct(cur.activity)+" active (retour prévu à "+TripHm(cur.returnAt)+"). Terminez-la avant d’en démarrer une autre."),x("Voir ma sortie "+TripAct(cur.activity),{kind:"primary",href:"#/sortie/"+(cur.activity==="peche"?"peche":"chasse")})),
Active=cur=>{let timer=e("div.sortie-timer",""),lbl=e("div.small.muted",""),late=e("div",{hidden:!0}),sync=()=>{let d=new Date(cur.returnAt)-Date.now(),isLate=d<0;timer.textContent=TripFmt(d);timer.className="sortie-timer "+(isLate?"state-late":"state-ok");lbl.textContent=isLate?"de retard sur l’heure de retour prévue ("+TripHm(cur.returnAt)+")":"avant l’heure de retour prévue ("+TripHm(cur.returnAt)+")";late.hidden=!isLate};sync();tick=setInterval(sync,1000);
late.append(e("div.sortie-late",b("alert"),e("div.grow",e("b","Heure de retour dépassée"),e("div.small","Confirmez que vous êtes rentré ou prolongez la sortie."+(cur.contact&&cur.contact.name?" Votre proche : "+cur.contact.name+(cur.contact.phone?" ("+cur.contact.phone+")":"")+".":"")))));
let ext=m=>x("+ "+(m<60?m+" min":m/60+" h"),{size:"sm",onClick:()=>{cur.returnAt=new Date(Math.max(Date.now(),new Date(cur.returnAt).getTime())+m*6e4).toISOString();cur.lateNotified=!1;TripEv(cur,"extend","Retour repoussé à "+TripHm(cur.returnAt)+" (+"+(m<60?m+" min":m/60+" h")+")");TripSet(cur);A("Retour repoussé à "+TripHm(cur.returnAt)+". Prévenez votre proche.","ok");render()}});
return e("div.grid.g-main",e("div.stack",late,k({},e("div.v2-hero",{style:{padding:"20px"}},e("div.pill-row",L(TripAct(cur.activity),"accent"),cur.place?L(cur.place):null,L("Départ "+TripHm(cur.start))),timer,lbl)),k({title:"À l’arrivée"},e("div.stack",{style:{gap:"12px"}},x("Je suis rentré",{icon:"check",kind:"primary",size:"block",onClick:async()=>{if(await ve({title:"Sortie terminée ?",text:"Votre proche peut être rassuré. N’oubliez pas de le prévenir.",confirm:"Je suis rentré"})){let h=Pe.get("trips-hist:"+u.id,[]);TripSample();cur=TripGet()||cur;TripEv(cur,"end","Retour confirmé");h.unshift({...cur,status:"done",endedAt:new Date().toISOString()});Pe.set("trips-hist:"+u.id,h.slice(0,50));TripSet(null);A("Bon retour ! Sortie terminée.","ok");render()}}}),e("div.row.wrap",{style:{gap:"8px"}},e("span.small.muted","Prolonger :"),ext(30),ext(60),ext(120)),x("Copier le message pour mon proche",{icon:"file",size:"block",onClick:()=>{TripEv(cur,"msg","Message copié pour "+(cur.contact&&cur.contact.name||"un proche"));TripSet(cur);TripCopy(TripMsg(cur))}}),x("Alerte SOS",{icon:"sos",kind:"danger",size:"block",onClick:()=>ht()})))),e("div.stack",k({title:"Mon proche"},e("div.list",e("div.list-row",e("span.ic",b("users")),e("div.grow",e("div.t",cur.contact.name||"—"),e("div.s",cur.contact.phone||"Pas de numéro enregistré")))),cur.note?e("p.small",{style:{margin:"10px 0 0"}},cur.note):null),LivePanel(cur,()=>render()),Prox()))};
render();return stop}

/* Niveaux d'eau (Hub'Eau, bêta) */
async function WaterView(t){let pos=w.position,out=e("div.stack"),st=e("div.small.muted",""),box=45e3;C(t,q({title:"Niveaux d’eau",subtitle:"Hauteur d’eau des stations de mesure proches de vous : monte, baisse ou stable. Données Hub’Eau (Eaufrance).",actions:[L("Bêta","warn")]},k({title:"Stations proches",sub:pos&&pos.approx?"Autour de la position par défaut":"Autour de votre position",action:x("Actualiser",{size:"sm",icon:"locate",onClick:()=>go()})},st,out)));
let go=async()=>{out.textContent="";st.textContent="Recherche des stations…";let p=w.position||{lat:47.6445,lng:2.181},dl=box/111320,dn=box/(111320*Math.cos(p.lat*Math.PI/180));try{let r=await fetch(`https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?bbox=${(p.lng-dn).toFixed(4)},${(p.lat-dl).toFixed(4)},${(p.lng+dn).toFixed(4)},${(p.lat+dl).toFixed(4)}&format=json&size=60`);if(!r.ok)throw new Error("HTTP "+r.status);let js=await r.json(),sts=(js.data||[]).filter(s1=>s1.code_station&&typeof s1.latitude_station==="number"&&typeof s1.longitude_station==="number"&&s1.en_service!==!1).map(s1=>({...s1,d:HavM(p,{lat:s1.latitude_station,lng:s1.longitude_station})})).sort((a,b2)=>a.d-b2.d).slice(0,6);if(!sts.length){st.textContent="Aucune station de mesure dans un rayon de 45 km. Déplacez-vous sur la carte ou essayez ailleurs.";return}st.textContent=sts.length+" station"+(sts.length>1?"s":"")+" trouvée"+(sts.length>1?"s":"")+", de la plus proche à la plus lointaine.";
for(let s1 of sts){let card=k({},e("div.water-card",e("div.grow",e("b",s1.libelle_station||s1.code_station),e("div.small.muted",(s1.libelle_cours_eau?s1.libelle_cours_eau+" · ":"")+Math.round(s1.d/100)/10+" km")),e("div.small.muted","Mesure en cours…")));out.append(card);
fetch(`https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=${encodeURIComponent(s1.code_station)}&grandeur_hydro=H&size=24&sort=desc&format=json`).then(z=>z.ok?z.json():Promise.reject(new Error("HTTP "+z.status))).then(z=>{let d=(z.data||[]).filter(o=>typeof o.resultat_obs==="number");card.textContent="";if(!d.length){card.append(e("div.small.muted",(s1.libelle_station||s1.code_station)+" : pas de mesure récente."));return}let last=d[0],old=d[d.length-1],dh=(last.resultat_obs-old.resultat_obs)/10,tr=Math.abs(dh)<1?"Stable":dh>0?"Monte":"Baisse";card.append(e("div.water-card",e("div.grow",e("b",s1.libelle_station||s1.code_station),e("div.small.muted",(s1.libelle_cours_eau?s1.libelle_cours_eau+" · ":"")+Math.round(s1.d/100)/10+" km · "+Ce(last.date_obs&&last.date_obs.length?last.date_obs:new Date().toISOString()).textContent)),e("div",{style:{textAlign:"right"}},e("div.water-val",Math.round(last.resultat_obs/10)+" cm"),L(tr+(Math.abs(dh)>=1?" ("+(dh>0?"+":"")+Math.round(dh)+" cm)":""),tr==="Monte"?"warn":tr==="Baisse"?"fish":"ok"))))}).catch(()=>{card.textContent="";card.append(e("div.small.muted",(s1.libelle_station||s1.code_station)+" : mesure indisponible."))})}}catch(er){st.textContent="Les données Hub’Eau ne sont pas joignables depuis cette page (réseau bloqué ou service indisponible). Cette fonction marche sur la version hébergée, avec internet."}};go();return()=>{}}

async function TripWake(){try{let tr=TripGet();if(!tr||tr.status!=="active"||!navigator.wakeLock||window._tripWl)return;window._tripWl=await navigator.wakeLock.request("screen");window._tripWl.addEventListener("release",()=>{window._tripWl=null})}catch{}}
