/* ===== 2.0 : outils de territoire (export, partage, territoire actif) ===== */
function TXml(s1){return String(s1).replace(/[<>&"']/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;","'":"&apos;"})[c])}
function TFile(q1,fmt){let nm=q1.name||"Territoire",b2=(q1.boundary||[]),pl=q1.places||[],slug=nm.normalize("NFD").replace(/[̀-ͯ]/g,"").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"territoire",ring=b2.length?[...b2,b2[0]]:[];
if(fmt==="geojson"){let f=[];b2.length&&f.push({type:"Feature",properties:{name:nm,kind:"territoire"},geometry:{type:"Polygon",coordinates:[ring.map(p=>[p[1],p[0]])]}});pl.forEach(p=>f.push({type:"Feature",properties:{name:p.name,type:p.type},geometry:{type:"Point",coordinates:[p.lng,p.lat]}}));return{name:slug+".geojson",mime:"application/geo+json",text:JSON.stringify({type:"FeatureCollection",features:f},null,1)}}
if(fmt==="kml")return{name:slug+".kml",mime:"application/vnd.google-earth.kml+xml",text:`<?xml version="1.0" encoding="UTF-8"?>\n<kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${TXml(nm)}</name>\n`+(b2.length?`<Placemark><name>${TXml(nm)}</name><Polygon><outerBoundaryIs><LinearRing><coordinates>${ring.map(p=>p[1]+","+p[0]+",0").join(" ")}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark>\n`:"")+pl.map(p=>`<Placemark><name>${TXml(p.name)}</name><description>${TXml(p.type||"")}</description><Point><coordinates>${p.lng},${p.lat},0</coordinates></Point></Placemark>`).join("\n")+`\n</Document></kml>`};
return{name:slug+".gpx",mime:"application/gpx+xml",text:`<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Chasse &amp; Pêche 360°" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>${TXml(nm)}</name></metadata>\n`+pl.map(p=>`<wpt lat="${p.lat}" lon="${p.lng}"><name>${TXml(p.name)}</name><desc>${TXml(p.type||"")}</desc></wpt>`).join("\n")+(b2.length?`\n<trk><name>${TXml(nm)}</name><trkseg>${ring.map(p=>`<trkpt lat="${p[0]}" lon="${p[1]}"/>`).join("")}</trkseg></trk>`:"")+`\n</gpx>`}}
function TDownload(f){let url=null,ok=!1;try{let bl=new Blob([f.text],{type:f.mime+";charset=utf-8"});url=URL.createObjectURL(bl);let a=e("a",{href:url,download:f.name,style:{display:"none"}});document.body.append(a);a.click();a.remove();ok=!0;setTimeout(()=>URL.revokeObjectURL(url),4e3)}catch{}return ok}
function TExportDlg(q1){let list=[["gpx","GPX","GPS de randonnée, Garmin, applis de navigation"],["kml","KML","Google Earth, Google Maps"],["geojson","GeoJSON","SIG, QGIS, usages techniques"]],m=Le({title:"Exporter « "+q1.name+" »",body:e("div.stack",{style:{gap:"10px"}},e("p.small.muted",{style:{margin:0}},"Choisissez un format. Si le téléchargement est bloqué par votre navigateur, utilisez « Copier »."),list.map(([k1,l,ds])=>{let f=TFile(q1,k1);return e("div.panel",{style:{padding:"12px 14px"}},e("div.row.wrap",{style:{gap:"10px"}},e("div.grow",e("b",l),e("div.small.muted",ds)),x("Télécharger",{size:"sm",icon:"download",onClick:()=>{TDownload(f)?A("Fichier "+f.name+" préparé.","ok"):A("Téléchargement indisponible ici : utilisez Copier.","warn")}}),x("Copier",{size:"sm",kind:"ghost",onClick:async()=>{try{await navigator.clipboard.writeText(f.text);A(l+" copié.","ok")}catch{A("Copie impossible : sélectionnez le texte manuellement.","warn")}}})))})),actions:[x("Fermer",{kind:"ghost",onClick:()=>m.close()})]})}
function TB64(o){let s1=JSON.stringify(o),by=new TextEncoder().encode(s1),bin="";by.forEach(c=>bin+=String.fromCharCode(c));return btoa(bin).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function TUn64(d){let s1=d.replace(/-/g,"+").replace(/_/g,"/");while(s1.length%4)s1+="=";let bin=atob(s1),by=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(by))}
function TShareDlg(q1){let r=n=>+(+n).toFixed(5),pay={n:q1.name,b:(q1.boundary||[]).map(p=>[r(p[0]),r(p[1])]),p:(q1.places||[]).slice(0,30).map(p=>({n:p.name,t:p.type||"",a:r(p.lat),o:r(p.lng)}))},tok=TB64(pay),base=location.href.split("#")[0],link=base+"#/partage/"+tok,inp=e("input.input",{type:"text",readonly:!0,value:link}),m=Le({title:"Partager « "+q1.name+" »",body:e("div.stack",{style:{gap:"10px"}},e("p.small",{style:{margin:0}},"Ce lien contient le tracé et les lieux. La personne qui l’ouvre voit le territoire en lecture seule, sans compte."),inp,link.length>2500?e("p.small",{style:{color:"var(--brick)",margin:0}},"Lien très long : certaines messageries pourraient le couper. Préférez un export GPX."):null,e("p.tiny.muted",{style:{margin:0}},"Le lien n’est pas stocké sur un serveur : toute personne qui le possède peut voir ces informations. Ne le diffusez qu’à des personnes de confiance.")),actions:[x("Fermer",{kind:"ghost",onClick:()=>m.close()}),x("Copier le lien",{kind:"primary",icon:"send",onClick:async()=>{try{await navigator.clipboard.writeText(link);A("Lien copié.","ok")}catch{inp.focus();inp.select();A("Sélectionnez puis copiez le lien.","warn")}}})]});setTimeout(()=>{inp.focus();inp.select()},60)}
function ShareView(t,pr){let d=null;try{d=TUn64((pr&&pr.data)||"")}catch{}
if(!d||!Array.isArray(d.b)||d.b.some(p=>!Array.isArray(p)||!isFinite(p[0])||!isFinite(p[1]))||d.b.length>500){C(t,q({title:"Lien de partage invalide"},V({icon:"alert",title:"Ce lien est incomplet ou abîmé",text:"Demandez à la personne de vous renvoyer le lien complet.",action:x("Retour",{href:"#/communaute"})})));return}
let u=e("div.map",{style:{height:"min(62vh,520px)"}}),pl=(d.p||[]).filter(p=>isFinite(p.a)&&isFinite(p.o));C(t,q({title:String(d.n||"Territoire partagé").slice(0,80),subtitle:"Territoire partagé en lecture seule.",actions:[L("Lecture seule","accent","eye")]},e("div.grid.g-main",e("div.stack",k({flush:!0},u)),e("div.stack",k({title:"Lieux repérés",sub:String(pl.length)},pl.length?e("div.list",pl.map(p=>e("div.list-row",e("span.ic",b("pin")),e("div.grow",e("div.t",p.n),e("div.s",p.t||"Lieu"))))):e("p.muted",{style:{margin:0}},"Aucun lieu.")),d.b.length>2?k({title:"Superficie estimée"},e("div",{style:{font:"700 28px var(--font-display)"}},M.num(TerrArea(d.b),1)+" ha")):null,k({cls:"tint"},e("p.small",{style:{margin:0}},"Vous avez un compte ? Ouvrez l’app pour délimiter votre propre territoire.")),w.user?null:x("Se connecter",{href:"#/connexion",kind:"primary",size:"block"})))));
try{let c0=d.b.length?[d.b.reduce((s1,p)=>s1+p[0],0)/d.b.length,d.b.reduce((s1,p)=>s1+p[1],0)/d.b.length]:pl.length?[pl[0].a,pl[0].o]:[47.6,2.2],m=De(u,{center:{lat:c0[0],lng:c0[1]},zoom:14}),L1=Ve();d.b.length>2&&L1.polygon(d.b,{color:"#2F6B4A",weight:3,fillOpacity:.14}).addTo(m);pl.forEach(p=>L1.circleMarker([p.a,p.o],{radius:8,color:"#fff",weight:2,fillColor:"#B6542F",fillOpacity:1}).bindTooltip(String(p.n)).addTo(m));at(m,[...d.b,...pl.map(p=>[p.a,p.o])])}catch{}}
function TerrActiveEl(){let body=e("div",e("p.small.muted",{style:{margin:0}},"Chargement…")),box=k({title:"Mon territoire actif",sub:"Où êtes-vous par rapport à lui ?"},body);(async()=>{try{let ls=(await v.get("/territories")).filter(z=>z.kind==="personal"&&(z.boundary||[]).length>2);body.textContent="";if(!ls.length){body.append(e("p.small.muted",{style:{margin:"0 0 10px"}},"Aucun territoire délimité. Ajoutez le vôtre pour savoir si vous êtes dessus."),x("Délimiter mon territoire",{size:"sm",icon:"plus",href:"#/carte?territoire=1"}));return}let id=Pe.get("terr-active:"+w.user.id,ls[0].id),cur=ls.find(z=>z.id===id)||ls[0],sel=e("select.input",{"aria-label":"Territoire actif",onchange:z=>{Pe.set("terr-active:"+w.user.id,z.target.value);cur=ls.find(q1=>q1.id===z.target.value);show()}},ls.map(z=>e("option",{value:z.id,selected:z.id===cur.id},z.name))),st=e("div",{style:{marginTop:"10px"}}),show=()=>{st.textContent="";let p=w.position;if(!p||p.approx){st.append(L("Position précise indisponible","warn"),e("p.tiny.muted",{style:{margin:"6px 0 0"}},"Activez la localisation (version hébergée) pour savoir si vous êtes sur votre territoire."));return}let ins=TIn(p,cur.boundary),d=ins?0:TDist(p,cur.boundary);st.append(ins?L("Vous êtes dans votre territoire","ok","check"):L("Hors de votre territoire · à "+(d<1e3?Math.round(d)+" m":(d/1e3).toFixed(1)+" km"),"warn","alert"))};body.append(sel,st);show()}catch{}})();return box}
function TIn(p,poly){let x1=p.lng,y1=p.lat,ins=!1;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let xi=poly[i][1],yi=poly[i][0],xj=poly[j][1],yj=poly[j][0];yi>y1!=yj>y1&&x1<(xj-xi)*(y1-yi)/(yj-yi)+xi&&(ins=!ins)}return ins}
function TDist(p,poly){let best=1/0;for(let i=0;i<poly.length;i++){let a=poly[i],b2=poly[(i+1)%poly.length],kx=111320*Math.cos(p.lat*Math.PI/180),ky=110540,ax=(a[1]-p.lng)*kx,ay=(a[0]-p.lat)*ky,bx=(b2[1]-p.lng)*kx,by=(b2[0]-p.lat)*ky,dx=bx-ax,dy=by-ay,l2=dx*dx+dy*dy,tt=l2?Math.max(0,Math.min(1,-(ax*dx+ay*dy)/l2)):0,cx=ax+tt*dx,cy=ay+tt*dy;best=Math.min(best,Math.hypot(cx,cy))}return best}

/* ===== 3.0 : accueil « carte d'abord » ===== */
function HomeMapEl(){let mapEl=e("div.home-map-canvas",{role:"img","aria-label":"Aperçu de la carte de votre territoire"}),chip=e("div.home-chip",e("span.dot"),e("span.txt","Ma position")),open=x("Ouvrir la carte",{icon:"map",size:"sm",kind:"primary",href:"#/carte"}),box=e("div.home-map",mapEl,chip,e("div.home-open",open));
setTimeout(async()=>{try{let p=w.position,m=De(mapEl,{center:p,zoom:15,controls:!1}),L1=Ve(),ls=[];try{ls=(await v.get("/territories")).filter(z=>z.kind==="personal"&&(z.boundary||[]).length>2)}catch{}
ls.forEach(z=>{L1.polygon(z.boundary,{color:"#3D5B48",weight:3,fillOpacity:.16,interactive:!1}).addTo(m);(z.places||[]).forEach(pl=>L1.circleMarker([pl.lat,pl.lng],{radius:7,color:"#fff",weight:2,fillColor:"#B6542F",fillOpacity:1,interactive:!1}).addTo(m))});
L1.marker([p.lat,p.lng],{icon:ue("me"),interactive:!1}).addTo(m);
try{m.dragging.disable();m.touchZoom.disable();m.doubleClickZoom.disable();m.scrollWheelZoom.disable();m.boxZoom.disable();m.keyboard.disable()}catch{}
if(ls.length){at(m,ls.flatMap(z=>z.boundary),{padding:[30,30]});let z0=ls[0],txt=chip.querySelector(".txt");if(p&&!p.approx){txt.textContent=TIn(p,z0.boundary)?"Vous êtes dans "+z0.name:"Hors de "+z0.name}else txt.textContent=z0.name}else chip.querySelector(".txt").textContent="Aucun territoire délimité"}catch{}},0);
mapEl.addEventListener("click",()=>{location.hash="#/carte"});return box}
